# jedec.sh -- JEDEC JEP106 manufacturer ID table for wellutils
# wu_jedec_decode <hex4>: decode "cckk" (continuation byte + code byte)
# from dmidecode Manufacturer field (e.g. 8313 -> Golden Empire).
# The vendor table is extracted from i2c-tools decode-dimms (@vendors),
# Copyright (c) 1999-2024 the i2c-tools authors (Jean Delvare et al.),
# GPL-2.0: https://i2c-tools.sourceforge.net/
# wellutils wrapper code is MIT; see LICENSE.
# shellcheck shell=bash
wu_jedec_decode() {
    local raw="$1" cnt cde idx
    raw=${raw// /}
    case "$raw" in
        [0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]) : ;;
        *) echo "$1"; return ;;
    esac
    cnt=$((16#${raw:0:2} & 127))
    cde=$((16#${raw:2:2} ))
    idx=$((cde-1))
    case "$cnt:$idx" in
        0:0) echo "AMD"; return 0 ;;
        0:1) echo "AMI"; return 0 ;;
        0:2) echo "Fairchild"; return 0 ;;
        0:3) echo "Fujitsu"; return 0 ;;
        0:4) echo "GTE"; return 0 ;;
        0:5) echo "Harris"; return 0 ;;
        0:6) echo "Hitachi"; return 0 ;;
        0:7) echo "Inmos"; return 0 ;;
        0:8) echo "Intel"; return 0 ;;
        0:9) echo "I.T.T."; return 0 ;;
        0:10) echo "Intersil"; return 0 ;;
        0:11) echo "Monolithic Memories"; return 0 ;;
        0:12) echo "Mostek"; return 0 ;;
        0:13) echo "Freescale (former Motorola)"; return 0 ;;
        0:14) echo "National"; return 0 ;;
        0:15) echo "NEC"; return 0 ;;
        0:16) echo "RCA"; return 0 ;;
        0:17) echo "Raytheon"; return 0 ;;
        0:18) echo "Conexant (Rockwell)"; return 0 ;;
        0:19) echo "Seeq"; return 0 ;;
        0:20) echo "NXP (former Signetics, Philips Semi.)"; return 0 ;;
        0:21) echo "Synertek"; return 0 ;;
        0:22) echo "Texas Instruments"; return 0 ;;
        0:23) echo "Kioxia Corporation (former Toshiba Memory Corporation)"; return 0 ;;
        0:24) echo "Xicor"; return 0 ;;
        0:25) echo "Zilog"; return 0 ;;
        0:26) echo "Eurotechnique"; return 0 ;;
        0:27) echo "Mitsubishi"; return 0 ;;
        0:28) echo "Lucent (AT&T)"; return 0 ;;
        0:29) echo "Exel"; return 0 ;;
        0:30) echo "Atmel"; return 0 ;;
        0:31) echo "STMicroelectronics (former SGS/Thomson)"; return 0 ;;
        0:32) echo "Lattice Semi."; return 0 ;;
        0:33) echo "NCR"; return 0 ;;
        0:34) echo "Wafer Scale Integration"; return 0 ;;
        0:35) echo "IBM"; return 0 ;;
        0:36) echo "Tristar"; return 0 ;;
        0:37) echo "Visic"; return 0 ;;
        0:38) echo "Intl. CMOS Technology"; return 0 ;;
        0:39) echo "SSSI"; return 0 ;;
        0:40) echo "MicrochipTechnology"; return 0 ;;
        0:41) echo "Ricoh Ltd."; return 0 ;;
        0:42) echo "VLSI"; return 0 ;;
        0:43) echo "Micron Technology"; return 0 ;;
        0:44) echo "SK Hynix (former Hyundai Electronics)"; return 0 ;;
        0:45) echo "OKI Semiconductor"; return 0 ;;
        0:46) echo "ACTEL"; return 0 ;;
        0:47) echo "Sharp"; return 0 ;;
        0:48) echo "Catalyst"; return 0 ;;
        0:49) echo "Panasonic"; return 0 ;;
        0:50) echo "IDT"; return 0 ;;
        0:51) echo "Cypress"; return 0 ;;
        0:52) echo "DEC"; return 0 ;;
        0:53) echo "LSI Logic"; return 0 ;;
        0:54) echo "Zarlink (former Plessey)"; return 0 ;;
        0:55) echo "UTMC"; return 0 ;;
        0:56) echo "Thinking Machine"; return 0 ;;
        0:57) echo "Thomson CSF"; return 0 ;;
        0:58) echo "Integrated CMOS (Vertex)"; return 0 ;;
        0:59) echo "Honeywell"; return 0 ;;
        0:60) echo "Tektronix"; return 0 ;;
        0:61) echo "Oracle Corporation (former Sun Microsystems)"; return 0 ;;
        0:62) echo "Silicon Storage Technology"; return 0 ;;
        0:63) echo "ProMos/Mosel Vitelic"; return 0 ;;
        0:64) echo "Infineon (former Siemens)"; return 0 ;;
        0:65) echo "Macronix"; return 0 ;;
        0:66) echo "Xerox"; return 0 ;;
        0:67) echo "Plus Logic"; return 0 ;;
        0:68) echo "Western Digital Technologies (former SanDisk Corporation)"; return 0 ;;
        0:69) echo "Elan Circuit Tech."; return 0 ;;
        0:70) echo "European Silicon Str."; return 0 ;;
        0:71) echo "Apple Computer"; return 0 ;;
        0:72) echo "Xilinx"; return 0 ;;
        0:73) echo "Compaq"; return 0 ;;
        0:74) echo "Protocol Engines"; return 0 ;;
        0:75) echo "SCI"; return 0 ;;
        0:76) echo "Seiko Instruments"; return 0 ;;
        0:77) echo "Samsung"; return 0 ;;
        0:78) echo "I3 Design System"; return 0 ;;
        0:79) echo "Klic"; return 0 ;;
        0:80) echo "Crosspoint Solutions"; return 0 ;;
        0:81) echo "Alliance Memory Inc"; return 0 ;;
        0:82) echo "Tandem"; return 0 ;;
        0:83) echo "Hewlett-Packard"; return 0 ;;
        0:84) echo "Integrated Silicon Solutions"; return 0 ;;
        0:85) echo "Brooktree"; return 0 ;;
        0:86) echo "New Media"; return 0 ;;
        0:87) echo "MHS Electronic"; return 0 ;;
        0:88) echo "Performance Semi."; return 0 ;;
        0:89) echo "Winbond Electronic"; return 0 ;;
        0:90) echo "Kawasaki Steel"; return 0 ;;
        0:91) echo "Bright Micro"; return 0 ;;
        0:92) echo "TECMAR"; return 0 ;;
        0:93) echo "Exar"; return 0 ;;
        0:94) echo "PCMCIA"; return 0 ;;
        0:95) echo "LG Semi (former Goldstar)"; return 0 ;;
        0:96) echo "Northern Telecom"; return 0 ;;
        0:97) echo "Sanyo"; return 0 ;;
        0:98) echo "Array Microsystems"; return 0 ;;
        0:99) echo "Crystal Semiconductor"; return 0 ;;
        0:100) echo "Analog Devices"; return 0 ;;
        0:101) echo "PMC-Sierra"; return 0 ;;
        0:102) echo "Asparix"; return 0 ;;
        0:103) echo "Convex Computer"; return 0 ;;
        0:104) echo "Quality Semiconductor"; return 0 ;;
        0:105) echo "Nimbus Technology"; return 0 ;;
        0:106) echo "Transwitch"; return 0 ;;
        0:107) echo "Micronas (ITT Intermetall)"; return 0 ;;
        0:108) echo "Cannon"; return 0 ;;
        0:109) echo "Altera"; return 0 ;;
        0:110) echo "NEXCOM"; return 0 ;;
        0:111) echo "QUALCOMM"; return 0 ;;
        0:112) echo "Sony"; return 0 ;;
        0:113) echo "Cray Research"; return 0 ;;
        0:114) echo "AMS(Austria Micro)"; return 0 ;;
        0:115) echo "Vitesse"; return 0 ;;
        0:116) echo "Aster Electronics"; return 0 ;;
        0:117) echo "Bay Networks (Synoptic)"; return 0 ;;
        0:118) echo "Zentrum or ZMD"; return 0 ;;
        0:119) echo "TRW"; return 0 ;;
        0:120) echo "Thesys"; return 0 ;;
        0:121) echo "Solbourne Computer"; return 0 ;;
        0:122) echo "Allied-Signal"; return 0 ;;
        0:123) echo "Dialog"; return 0 ;;
        0:124) echo "Media Vision"; return 0 ;;
        0:125) echo "Numonyx Corporation (former Level One Communication)"; return 0 ;;
        1:0) echo "Cirrus Logic"; return 0 ;;
        1:1) echo "National Instruments"; return 0 ;;
        1:2) echo "ILC Data Device"; return 0 ;;
        1:3) echo "Alcatel Mietec"; return 0 ;;
        1:4) echo "Micro Linear"; return 0 ;;
        1:5) echo "Univ. of NC"; return 0 ;;
        1:6) echo "JTAG Technologies"; return 0 ;;
        1:7) echo "BAE Systems"; return 0 ;;
        1:8) echo "Nchip"; return 0 ;;
        1:9) echo "Galileo Tech"; return 0 ;;
        1:10) echo "Bestlink Systems"; return 0 ;;
        1:11) echo "Graychip"; return 0 ;;
        1:12) echo "GENNUM"; return 0 ;;
        1:13) echo "VideoLogic"; return 0 ;;
        1:14) echo "Robert Bosch"; return 0 ;;
        1:15) echo "Chip Express"; return 0 ;;
        1:16) echo "DATARAM"; return 0 ;;
        1:17) echo "United Microelec Corp."; return 0 ;;
        1:18) echo "TCSI"; return 0 ;;
        1:19) echo "Smart Modular"; return 0 ;;
        1:20) echo "Hughes Aircraft"; return 0 ;;
        1:21) echo "Lanstar Semiconductor"; return 0 ;;
        1:22) echo "Qlogic"; return 0 ;;
        1:23) echo "Kingston"; return 0 ;;
        1:24) echo "Music Semi"; return 0 ;;
        1:25) echo "Ericsson Components"; return 0 ;;
        1:26) echo "SpaSE"; return 0 ;;
        1:27) echo "Eon Silicon Devices"; return 0 ;;
        1:28) echo "Integrated Silicon Solution (ISSI) (former Programmable Micro Corp)"; return 0 ;;
        1:29) echo "DoD"; return 0 ;;
        1:30) echo "Integ. Memories Tech."; return 0 ;;
        1:31) echo "Corollary Inc."; return 0 ;;
        1:32) echo "Dallas Semiconductor"; return 0 ;;
        1:33) echo "Omnivision"; return 0 ;;
        1:34) echo "EIV(Switzerland)"; return 0 ;;
        1:35) echo "Novatel Wireless"; return 0 ;;
        1:36) echo "Zarlink (former Mitel)"; return 0 ;;
        1:37) echo "Clearpoint"; return 0 ;;
        1:38) echo "Cabletron"; return 0 ;;
        1:39) echo "STEC (former Silicon Technology)"; return 0 ;;
        1:40) echo "Vanguard"; return 0 ;;
        1:41) echo "Hagiwara Sys-Com"; return 0 ;;
        1:42) echo "Vantis"; return 0 ;;
        1:43) echo "Celestica"; return 0 ;;
        1:44) echo "Century"; return 0 ;;
        1:45) echo "Hal Computers"; return 0 ;;
        1:46) echo "Rohm Company Ltd."; return 0 ;;
        1:47) echo "Juniper Networks"; return 0 ;;
        1:48) echo "Libit Signal Processing"; return 0 ;;
        1:49) echo "Mushkin Enhanced Memory"; return 0 ;;
        1:50) echo "Tundra Semiconductor"; return 0 ;;
        1:51) echo "Adaptec Inc."; return 0 ;;
        1:52) echo "LightSpeed Semi."; return 0 ;;
        1:53) echo "ZSP Corp."; return 0 ;;
        1:54) echo "AMIC Technology"; return 0 ;;
        1:55) echo "Adobe Systems"; return 0 ;;
        1:56) echo "Dynachip"; return 0 ;;
        1:57) echo "PNY Technologies Inc. (former PNY Electronics)"; return 0 ;;
        1:58) echo "Newport Digital"; return 0 ;;
        1:59) echo "MMC Networks"; return 0 ;;
        1:60) echo "T Square"; return 0 ;;
        1:61) echo "Seiko Epson"; return 0 ;;
        1:62) echo "Broadcom"; return 0 ;;
        1:63) echo "Viking Components"; return 0 ;;
        1:64) echo "V3 Semiconductor"; return 0 ;;
        1:65) echo "Flextronics (former Orbit)"; return 0 ;;
        1:66) echo "Suwa Electronics"; return 0 ;;
        1:67) echo "Transmeta"; return 0 ;;
        1:68) echo "Micron CMS"; return 0 ;;
        1:69) echo "American Computer & Digital Components Inc"; return 0 ;;
        1:70) echo "Enhance 3000 Inc"; return 0 ;;
        1:71) echo "Tower Semiconductor"; return 0 ;;
        1:72) echo "CPU Design"; return 0 ;;
        1:73) echo "Price Point"; return 0 ;;
        1:74) echo "Maxim Integrated Product"; return 0 ;;
        1:75) echo "Tellabs"; return 0 ;;
        1:76) echo "Centaur Technology"; return 0 ;;
        1:77) echo "Unigen Corporation"; return 0 ;;
        1:78) echo "Transcend Information"; return 0 ;;
        1:79) echo "Memory Card Technology"; return 0 ;;
        1:80) echo "CKD Corporation Ltd."; return 0 ;;
        1:81) echo "Capital Instruments, Inc."; return 0 ;;
        1:82) echo "Aica Kogyo, Ltd."; return 0 ;;
        1:83) echo "Linvex Technology"; return 0 ;;
        1:84) echo "MSC Vertriebs GmbH"; return 0 ;;
        1:85) echo "AKM Company, Ltd."; return 0 ;;
        1:86) echo "Dynamem, Inc."; return 0 ;;
        1:87) echo "NERA ASA"; return 0 ;;
        1:88) echo "GSI Technology"; return 0 ;;
        1:89) echo "Dane-Elec (C Memory)"; return 0 ;;
        1:90) echo "Acorn Computers"; return 0 ;;
        1:91) echo "Lara Technology"; return 0 ;;
        1:92) echo "Oak Technology, Inc."; return 0 ;;
        1:93) echo "Itec Memory"; return 0 ;;
        1:94) echo "Tanisys Technology"; return 0 ;;
        1:95) echo "Truevision"; return 0 ;;
        1:96) echo "Wintec Industries"; return 0 ;;
        1:97) echo "Super PC Memory"; return 0 ;;
        1:98) echo "MGV Memory"; return 0 ;;
        1:99) echo "Galvantech"; return 0 ;;
        1:100) echo "Gadzoox Nteworks"; return 0 ;;
        1:101) echo "Multi Dimensional Cons."; return 0 ;;
        1:102) echo "GateField"; return 0 ;;
        1:103) echo "Integrated Memory System"; return 0 ;;
        1:104) echo "Triscend"; return 0 ;;
        1:105) echo "XaQti"; return 0 ;;
        1:106) echo "Goldenram"; return 0 ;;
        1:107) echo "Clear Logic"; return 0 ;;
        1:108) echo "Cimaron Communications"; return 0 ;;
        1:109) echo "Nippon Steel Semi. Corp."; return 0 ;;
        1:110) echo "Advantage Memory"; return 0 ;;
        1:111) echo "AMCC"; return 0 ;;
        1:112) echo "LeCroy"; return 0 ;;
        1:113) echo "Yamaha Corporation"; return 0 ;;
        1:114) echo "Digital Microwave"; return 0 ;;
        1:115) echo "NetLogic Microsystems"; return 0 ;;
        1:116) echo "MIMOS Semiconductor"; return 0 ;;
        1:117) echo "Advanced Fibre"; return 0 ;;
        1:118) echo "BF Goodrich Data."; return 0 ;;
        1:119) echo "Epigram"; return 0 ;;
        1:120) echo "Acbel Polytech Inc."; return 0 ;;
        1:121) echo "Apacer Technology"; return 0 ;;
        1:122) echo "Admor Memory"; return 0 ;;
        1:123) echo "FOXCONN"; return 0 ;;
        1:124) echo "Quadratics Superconductor"; return 0 ;;
        1:125) echo "3COM"; return 0 ;;
        2:0) echo "Camintonn Corporation"; return 0 ;;
        2:1) echo "ISOA Incorporated"; return 0 ;;
        2:2) echo "Agate Semiconductor"; return 0 ;;
        2:3) echo "ADMtek Incorporated"; return 0 ;;
        2:4) echo "HYPERTEC"; return 0 ;;
        2:5) echo "Adhoc Technologies"; return 0 ;;
        2:6) echo "MOSAID Technologies"; return 0 ;;
        2:7) echo "Ardent Technologies"; return 0 ;;
        2:8) echo "Switchcore"; return 0 ;;
        2:9) echo "Cisco Systems, Inc."; return 0 ;;
        2:10) echo "Allayer Technologies"; return 0 ;;
        2:11) echo "WorkX AG (Wichman)"; return 0 ;;
        2:12) echo "Oasis Semiconductor"; return 0 ;;
        2:13) echo "Novanet Semiconductor"; return 0 ;;
        2:14) echo "E-M Solutions"; return 0 ;;
        2:15) echo "Power General"; return 0 ;;
        2:16) echo "Advanced Hardware Arch."; return 0 ;;
        2:17) echo "Inova Semiconductors GmbH"; return 0 ;;
        2:18) echo "Telocity"; return 0 ;;
        2:19) echo "Delkin Devices"; return 0 ;;
        2:20) echo "Symagery Microsystems"; return 0 ;;
        2:21) echo "C-Port Corporation"; return 0 ;;
        2:22) echo "SiberCore Technologies"; return 0 ;;
        2:23) echo "Southland Microsystems"; return 0 ;;
        2:24) echo "Malleable Technologies"; return 0 ;;
        2:25) echo "Kendin Communications"; return 0 ;;
        2:26) echo "Great Technology Microcomputer"; return 0 ;;
        2:27) echo "Sanmina Corporation"; return 0 ;;
        2:28) echo "HADCO Corporation"; return 0 ;;
        2:29) echo "Corsair"; return 0 ;;
        2:30) echo "Actrans System Inc."; return 0 ;;
        2:31) echo "ALPHA Technologies"; return 0 ;;
        2:32) echo "Silicon Laboratories, Inc. (Cygnal)"; return 0 ;;
        2:33) echo "Artesyn Technologies"; return 0 ;;
        2:34) echo "Align Manufacturing"; return 0 ;;
        2:35) echo "Peregrine Semiconductor"; return 0 ;;
        2:36) echo "Chameleon Systems"; return 0 ;;
        2:37) echo "Aplus Flash Technology"; return 0 ;;
        2:38) echo "MIPS Technologies"; return 0 ;;
        2:39) echo "Chrysalis ITS"; return 0 ;;
        2:40) echo "ADTEC Corporation"; return 0 ;;
        2:41) echo "Kentron Technologies"; return 0 ;;
        2:42) echo "Win Technologies"; return 0 ;;
        2:43) echo "Tezzaron Semiconductor (former Tachyon Semiconductor)"; return 0 ;;
        2:44) echo "Extreme Packet Devices"; return 0 ;;
        2:45) echo "RF Micro Devices"; return 0 ;;
        2:46) echo "Siemens AG"; return 0 ;;
        2:47) echo "Sarnoff Corporation"; return 0 ;;
        2:48) echo "Itautec SA (former Itautec Philco SA)"; return 0 ;;
        2:49) echo "Radiata Inc."; return 0 ;;
        2:50) echo "Benchmark Elect. (AVEX)"; return 0 ;;
        2:51) echo "Legend"; return 0 ;;
        2:52) echo "SpecTek Incorporated"; return 0 ;;
        2:53) echo "Hi/fn"; return 0 ;;
        2:54) echo "Enikia Incorporated"; return 0 ;;
        2:55) echo "SwitchOn Networks"; return 0 ;;
        2:56) echo "AANetcom Incorporated"; return 0 ;;
        2:57) echo "Micro Memory Bank"; return 0 ;;
        2:58) echo "ESS Technology"; return 0 ;;
        2:59) echo "Virata Corporation"; return 0 ;;
        2:60) echo "Excess Bandwidth"; return 0 ;;
        2:61) echo "West Bay Semiconductor"; return 0 ;;
        2:62) echo "DSP Group"; return 0 ;;
        2:63) echo "Newport Communications"; return 0 ;;
        2:64) echo "Chip2Chip Incorporated"; return 0 ;;
        2:65) echo "Phobos Corporation"; return 0 ;;
        2:66) echo "Intellitech Corporation"; return 0 ;;
        2:67) echo "Nordic VLSI ASA"; return 0 ;;
        2:68) echo "Ishoni Networks"; return 0 ;;
        2:69) echo "Silicon Spice"; return 0 ;;
        2:70) echo "Alchemy Semiconductor"; return 0 ;;
        2:71) echo "Agilent Technologies"; return 0 ;;
        2:72) echo "Centillium Communications"; return 0 ;;
        2:73) echo "W.L. Gore"; return 0 ;;
        2:74) echo "HanBit Electronics"; return 0 ;;
        2:75) echo "GlobeSpan"; return 0 ;;
        2:76) echo "Element 14"; return 0 ;;
        2:77) echo "Pycon"; return 0 ;;
        2:78) echo "Saifun Semiconductors"; return 0 ;;
        2:79) echo "Sibyte, Incorporated"; return 0 ;;
        2:80) echo "MetaLink Technologies"; return 0 ;;
        2:81) echo "Feiya Technology"; return 0 ;;
        2:82) echo "I & C Technology"; return 0 ;;
        2:83) echo "Shikatronics"; return 0 ;;
        2:84) echo "Elektrobit"; return 0 ;;
        2:85) echo "Megic"; return 0 ;;
        2:86) echo "Com-Tier"; return 0 ;;
        2:87) echo "Malaysia Micro Solutions"; return 0 ;;
        2:88) echo "Hyperchip"; return 0 ;;
        2:89) echo "Gemstone Communications"; return 0 ;;
        2:90) echo "Anadigm (former Anadyne)"; return 0 ;;
        2:91) echo "3ParData"; return 0 ;;
        2:92) echo "Mellanox Technologies"; return 0 ;;
        2:93) echo "Tenx Technologies"; return 0 ;;
        2:94) echo "Helix AG"; return 0 ;;
        2:95) echo "Domosys"; return 0 ;;
        2:96) echo "Skyup Technology"; return 0 ;;
        2:97) echo "HiNT Corporation"; return 0 ;;
        2:98) echo "Chiaro"; return 0 ;;
        2:99) echo "MDT Technologies GmbH (former MCI Computer GMBH)"; return 0 ;;
        2:100) echo "Exbit Technology A/S"; return 0 ;;
        2:101) echo "Integrated Technology Express"; return 0 ;;
        2:102) echo "AVED Memory"; return 0 ;;
        2:103) echo "Legerity"; return 0 ;;
        2:104) echo "Jasmine Networks"; return 0 ;;
        2:105) echo "Caspian Networks"; return 0 ;;
        2:106) echo "nCUBE"; return 0 ;;
        2:107) echo "Silicon Access Networks"; return 0 ;;
        2:108) echo "FDK Corporation"; return 0 ;;
        2:109) echo "High Bandwidth Access"; return 0 ;;
        2:110) echo "MultiLink Technology"; return 0 ;;
        2:111) echo "BRECIS"; return 0 ;;
        2:112) echo "World Wide Packets"; return 0 ;;
        2:113) echo "APW"; return 0 ;;
        2:114) echo "Chicory Systems"; return 0 ;;
        2:115) echo "Xstream Logic"; return 0 ;;
        2:116) echo "Fast-Chip"; return 0 ;;
        2:117) echo "Zucotto Wireless"; return 0 ;;
        2:118) echo "Realchip"; return 0 ;;
        2:119) echo "Galaxy Power"; return 0 ;;
        2:120) echo "eSilicon"; return 0 ;;
        2:121) echo "Morphics Technology"; return 0 ;;
        2:122) echo "Accelerant Networks"; return 0 ;;
        2:123) echo "Silicon Wave"; return 0 ;;
        2:124) echo "SandCraft"; return 0 ;;
        2:125) echo "Elpida"; return 0 ;;
        3:0) echo "Solectron"; return 0 ;;
        3:1) echo "Optosys Technologies"; return 0 ;;
        3:2) echo "Buffalo (former Melco)"; return 0 ;;
        3:3) echo "TriMedia Technologies"; return 0 ;;
        3:4) echo "Cyan Technologies"; return 0 ;;
        3:5) echo "Global Locate"; return 0 ;;
        3:6) echo "Optillion"; return 0 ;;
        3:7) echo "Terago Communications"; return 0 ;;
        3:8) echo "Ikanos Communications"; return 0 ;;
        3:9) echo "Princeton Technology"; return 0 ;;
        3:10) echo "Nanya Technology"; return 0 ;;
        3:11) echo "Elite Flash Storage"; return 0 ;;
        3:12) echo "Mysticom"; return 0 ;;
        3:13) echo "LightSand Communications"; return 0 ;;
        3:14) echo "ATI Technologies"; return 0 ;;
        3:15) echo "Agere Systems"; return 0 ;;
        3:16) echo "NeoMagic"; return 0 ;;
        3:17) echo "AuroraNetics"; return 0 ;;
        3:18) echo "Golden Empire"; return 0 ;;
        3:19) echo "Mushkin"; return 0 ;;
        3:20) echo "Tioga Technologies"; return 0 ;;
        3:21) echo "Netlist"; return 0 ;;
        3:22) echo "TeraLogic"; return 0 ;;
        3:23) echo "Cicada Semiconductor"; return 0 ;;
        3:24) echo "Centon Electronics"; return 0 ;;
        3:25) echo "Tyco Electronics"; return 0 ;;
        3:26) echo "Magis Works"; return 0 ;;
        3:27) echo "Zettacom"; return 0 ;;
        3:28) echo "Cogency Semiconductor"; return 0 ;;
        3:29) echo "Chipcon AS"; return 0 ;;
        3:30) echo "Aspex Technology"; return 0 ;;
        3:31) echo "F5 Networks"; return 0 ;;
        3:32) echo "Programmable Silicon Solutions"; return 0 ;;
        3:33) echo "ChipWrights"; return 0 ;;
        3:34) echo "Acorn Networks"; return 0 ;;
        3:35) echo "Quicklogic"; return 0 ;;
        3:36) echo "Kingmax Semiconductor"; return 0 ;;
        3:37) echo "BOPS"; return 0 ;;
        3:38) echo "Flasys"; return 0 ;;
        3:39) echo "BitBlitz Communications"; return 0 ;;
        3:40) echo "eMemory Technology"; return 0 ;;
        3:41) echo "Procket Networks"; return 0 ;;
        3:42) echo "Purple Ray"; return 0 ;;
        3:43) echo "Trebia Networks"; return 0 ;;
        3:44) echo "Delta Electronics"; return 0 ;;
        3:45) echo "Onex Communications"; return 0 ;;
        3:46) echo "Ample Communications"; return 0 ;;
        3:47) echo "Memory Experts Intl"; return 0 ;;
        3:48) echo "Astute Networks"; return 0 ;;
        3:49) echo "Azanda Network Devices"; return 0 ;;
        3:50) echo "Dibcom"; return 0 ;;
        3:51) echo "Tekmos"; return 0 ;;
        3:52) echo "API NetWorks"; return 0 ;;
        3:53) echo "Bay Microsystems"; return 0 ;;
        3:54) echo "Firecron Ltd"; return 0 ;;
        3:55) echo "Resonext Communications"; return 0 ;;
        3:56) echo "Tachys Technologies"; return 0 ;;
        3:57) echo "Equator Technology"; return 0 ;;
        3:58) echo "Concept Computer"; return 0 ;;
        3:59) echo "SILCOM"; return 0 ;;
        3:60) echo "3Dlabs"; return 0 ;;
        3:61) echo "c't Magazine"; return 0 ;;
        3:62) echo "Sanera Systems"; return 0 ;;
        3:63) echo "Silicon Packets"; return 0 ;;
        3:64) echo "Viasystems Group"; return 0 ;;
        3:65) echo "Simtek"; return 0 ;;
        3:66) echo "Semicon Devices Singapore"; return 0 ;;
        3:67) echo "Satron Handelsges"; return 0 ;;
        3:68) echo "Improv Systems"; return 0 ;;
        3:69) echo "INDUSYS GmbH"; return 0 ;;
        3:70) echo "Corrent"; return 0 ;;
        3:71) echo "Infrant Technologies"; return 0 ;;
        3:72) echo "Ritek Corp"; return 0 ;;
        3:73) echo "empowerTel Networks"; return 0 ;;
        3:74) echo "Hypertec"; return 0 ;;
        3:75) echo "Cavium Networks"; return 0 ;;
        3:76) echo "PLX Technology"; return 0 ;;
        3:77) echo "Massana Design"; return 0 ;;
        3:78) echo "Intrinsity"; return 0 ;;
        3:79) echo "Valence Semiconductor"; return 0 ;;
        3:80) echo "Terawave Communications"; return 0 ;;
        3:81) echo "IceFyre Semiconductor"; return 0 ;;
        3:82) echo "Primarion"; return 0 ;;
        3:83) echo "Picochip Designs Ltd"; return 0 ;;
        3:84) echo "Silverback Systems"; return 0 ;;
        3:85) echo "Jade Star Technologies"; return 0 ;;
        3:86) echo "Pijnenburg Securealink"; return 0 ;;
        3:87) echo "takeMS - Ultron AG (former Memorysolution GmbH)"; return 0 ;;
        3:88) echo "Cambridge Silicon Radio"; return 0 ;;
        3:89) echo "Swissbit"; return 0 ;;
        3:90) echo "Nazomi Communications"; return 0 ;;
        3:91) echo "eWave System"; return 0 ;;
        3:92) echo "Rockwell Collins"; return 0 ;;
        3:93) echo "Picocel Co., Ltd."; return 0 ;;
        3:94) echo "Alphamosaic Ltd"; return 0 ;;
        3:95) echo "Sandburst"; return 0 ;;
        3:96) echo "SiCon Video"; return 0 ;;
        3:97) echo "NanoAmp Solutions"; return 0 ;;
        3:98) echo "Ericsson Technology"; return 0 ;;
        3:99) echo "PrairieComm"; return 0 ;;
        3:100) echo "Mitac International"; return 0 ;;
        3:101) echo "Layer N Networks"; return 0 ;;
        3:102) echo "MtekVision"; return 0 ;;
        3:103) echo "Allegro Networks"; return 0 ;;
        3:104) echo "Marvell Semiconductors"; return 0 ;;
        3:105) echo "Netergy Microelectronic"; return 0 ;;
        3:106) echo "NVIDIA"; return 0 ;;
        3:107) echo "Internet Machines"; return 0 ;;
        3:108) echo "Memorysolution GmbH (former Peak Electronics)"; return 0 ;;
        3:109) echo "Litchfield Communication"; return 0 ;;
        3:110) echo "Accton Technology"; return 0 ;;
        3:111) echo "Teradiant Networks"; return 0 ;;
        3:112) echo "Scaleo Chip (former Europe Technologies)"; return 0 ;;
        3:113) echo "Cortina Systems"; return 0 ;;
        3:114) echo "RAM Components"; return 0 ;;
        3:115) echo "Raqia Networks"; return 0 ;;
        3:116) echo "ClearSpeed"; return 0 ;;
        3:117) echo "Matsushita Battery"; return 0 ;;
        3:118) echo "Xelerated"; return 0 ;;
        3:119) echo "SimpleTech"; return 0 ;;
        3:120) echo "Utron Technology"; return 0 ;;
        3:121) echo "Astec International"; return 0 ;;
        3:122) echo "AVM gmbH"; return 0 ;;
        3:123) echo "Redux Communications"; return 0 ;;
        3:124) echo "Dot Hill Systems"; return 0 ;;
        3:125) echo "TeraChip"; return 0 ;;
        4:0) echo "T-RAM Incorporated"; return 0 ;;
        4:1) echo "Innovics Wireless"; return 0 ;;
        4:2) echo "Teknovus"; return 0 ;;
        4:3) echo "KeyEye Communications"; return 0 ;;
        4:4) echo "Runcom Technologies"; return 0 ;;
        4:5) echo "RedSwitch"; return 0 ;;
        4:6) echo "Dotcast"; return 0 ;;
        4:7) echo "Silicon Mountain Memory"; return 0 ;;
        4:8) echo "Signia Technologies"; return 0 ;;
        4:9) echo "Pixim"; return 0 ;;
        4:10) echo "Galazar Networks"; return 0 ;;
        4:11) echo "White Electronic Designs"; return 0 ;;
        4:12) echo "Patriot Scientific"; return 0 ;;
        4:13) echo "Neoaxiom Corporation"; return 0 ;;
        4:14) echo "3Y Power Technology"; return 0 ;;
        4:15) echo "Scaleo Chip (former Europe Technologies)"; return 0 ;;
        4:16) echo "Potentia Power Systems"; return 0 ;;
        4:17) echo "C-guys Incorporated"; return 0 ;;
        4:18) echo "Digital Communications Technology Incorporated"; return 0 ;;
        4:19) echo "Silicon-Based Technology"; return 0 ;;
        4:20) echo "Fulcrum Microsystems"; return 0 ;;
        4:21) echo "Positivo Informatica Ltd"; return 0 ;;
        4:22) echo "XIOtech Corporation"; return 0 ;;
        4:23) echo "PortalPlayer"; return 0 ;;
        4:24) echo "Zhiying Software"; return 0 ;;
        4:25) echo "Parker Vision, Inc. (former Direct2Data)"; return 0 ;;
        4:26) echo "Phonex Broadband"; return 0 ;;
        4:27) echo "Skyworks Solutions"; return 0 ;;
        4:28) echo "Entropic Communications"; return 0 ;;
        4:29) echo "I'M Intelligent Memory Ltd (former Pacific Force Technology)"; return 0 ;;
        4:30) echo "Zensys A/S"; return 0 ;;
        4:31) echo "Legend Silicon Corp."; return 0 ;;
        4:32) echo "sci-worx GmbH"; return 0 ;;
        4:33) echo "SMSC (former Oasis Silicon Systems)"; return 0 ;;
        4:34) echo "Renesas Electronics (former Renesas Technology)"; return 0 ;;
        4:35) echo "Raza Microelectronics"; return 0 ;;
        4:36) echo "Phyworks"; return 0 ;;
        4:37) echo "MediaTek"; return 0 ;;
        4:38) echo "Non-cents Productions"; return 0 ;;
        4:39) echo "US Modular"; return 0 ;;
        4:40) echo "Wintegra Ltd"; return 0 ;;
        4:41) echo "Mathstar"; return 0 ;;
        4:42) echo "StarCore"; return 0 ;;
        4:43) echo "Oplus Technologies"; return 0 ;;
        4:44) echo "Mindspeed"; return 0 ;;
        4:45) echo "Just Young Computer"; return 0 ;;
        4:46) echo "Radia Communications"; return 0 ;;
        4:47) echo "OCZ"; return 0 ;;
        4:48) echo "Emuzed"; return 0 ;;
        4:49) echo "LOGIC Devices"; return 0 ;;
        4:50) echo "Inphi Corporation"; return 0 ;;
        4:51) echo "Quake Technologies"; return 0 ;;
        4:52) echo "Vixel"; return 0 ;;
        4:53) echo "SolusTek"; return 0 ;;
        4:54) echo "Kongsberg Maritime"; return 0 ;;
        4:55) echo "Faraday Technology"; return 0 ;;
        4:56) echo "Altium Ltd."; return 0 ;;
        4:57) echo "Insyte"; return 0 ;;
        4:58) echo "ARM Ltd."; return 0 ;;
        4:59) echo "DigiVision"; return 0 ;;
        4:60) echo "Vativ Technologies"; return 0 ;;
        4:61) echo "Endicott Interconnect Technologies"; return 0 ;;
        4:62) echo "Pericom"; return 0 ;;
        4:63) echo "Bandspeed"; return 0 ;;
        4:64) echo "LeWiz Communications"; return 0 ;;
        4:65) echo "CPU Technology"; return 0 ;;
        4:66) echo "Ramaxel Technology"; return 0 ;;
        4:67) echo "DSP Group"; return 0 ;;
        4:68) echo "Axis Communications"; return 0 ;;
        4:69) echo "Legacy Electronics"; return 0 ;;
        4:70) echo "Chrontel"; return 0 ;;
        4:71) echo "Powerchip Semiconductor"; return 0 ;;
        4:72) echo "MobilEye Technologies"; return 0 ;;
        4:73) echo "Excel Semiconductor"; return 0 ;;
        4:74) echo "A-DATA Technology"; return 0 ;;
        4:75) echo "VirtualDigm"; return 0 ;;
        4:76) echo "G Skill Intl"; return 0 ;;
        4:77) echo "Quanta Computer"; return 0 ;;
        4:78) echo "Yield Microelectronics"; return 0 ;;
        4:79) echo "Afa Technologies"; return 0 ;;
        4:80) echo "KINGBOX Technology Co. Ltd."; return 0 ;;
        4:81) echo "Ceva"; return 0 ;;
        4:82) echo "iStor Networks"; return 0 ;;
        4:83) echo "Advance Modules"; return 0 ;;
        4:84) echo "Microsoft"; return 0 ;;
        4:85) echo "Open-Silicon"; return 0 ;;
        4:86) echo "Goal Semiconductor"; return 0 ;;
        4:87) echo "ARC International"; return 0 ;;
        4:88) echo "Simmtec"; return 0 ;;
        4:89) echo "Metanoia"; return 0 ;;
        4:90) echo "Key Stream"; return 0 ;;
        4:91) echo "Lowrance Electronics"; return 0 ;;
        4:92) echo "Adimos"; return 0 ;;
        4:93) echo "SiGe Semiconductor"; return 0 ;;
        4:94) echo "Fodus Communications"; return 0 ;;
        4:95) echo "Credence Systems Corp."; return 0 ;;
        4:96) echo "Genesis Microchip Inc."; return 0 ;;
        4:97) echo "Vihana, Inc."; return 0 ;;
        4:98) echo "WIS Technologies"; return 0 ;;
        4:99) echo "GateChange Technologies"; return 0 ;;
        4:100) echo "High Density Devices AS"; return 0 ;;
        4:101) echo "Synopsys"; return 0 ;;
        4:102) echo "Gigaram"; return 0 ;;
        4:103) echo "Enigma Semiconductor Inc."; return 0 ;;
        4:104) echo "Century Micro Inc."; return 0 ;;
        4:105) echo "Icera Semiconductor"; return 0 ;;
        4:106) echo "Mediaworks Integrated Systems"; return 0 ;;
        4:107) echo "O'Neil Product Development"; return 0 ;;
        4:108) echo "Supreme Top Technology Ltd."; return 0 ;;
        4:109) echo "MicroDisplay Corporation"; return 0 ;;
        4:110) echo "Team Group Inc."; return 0 ;;
        4:111) echo "Sinett Corporation"; return 0 ;;
        4:112) echo "Toshiba Corporation"; return 0 ;;
        4:113) echo "Tensilica"; return 0 ;;
        4:114) echo "SiRF Technology"; return 0 ;;
        4:115) echo "Bacoc Inc."; return 0 ;;
        4:116) echo "SMaL Camera Technologies"; return 0 ;;
        4:117) echo "Thomson SC"; return 0 ;;
        4:118) echo "Airgo Networks"; return 0 ;;
        4:119) echo "Wisair Ltd."; return 0 ;;
        4:120) echo "SigmaTel"; return 0 ;;
        4:121) echo "Arkados"; return 0 ;;
        4:122) echo "Compete IT gmbH Co. KG"; return 0 ;;
        4:123) echo "Eudar Technology Inc."; return 0 ;;
        4:124) echo "Focus Enhancements"; return 0 ;;
        4:125) echo "Xyratex"; return 0 ;;
        5:0) echo "Specular Networks"; return 0 ;;
        5:1) echo "Patriot Memory"; return 0 ;;
        5:2) echo "U-Chip Technology Corp."; return 0 ;;
        5:3) echo "Silicon Optix"; return 0 ;;
        5:4) echo "Greenfield Networks"; return 0 ;;
        5:5) echo "CompuRAM GmbH"; return 0 ;;
        5:6) echo "Stargen, Inc."; return 0 ;;
        5:7) echo "NetCell Corporation"; return 0 ;;
        5:8) echo "Excalibrus Technologies Ltd"; return 0 ;;
        5:9) echo "SCM Microsystems"; return 0 ;;
        5:10) echo "Xsigo Systems, Inc."; return 0 ;;
        5:11) echo "CHIPS & Systems Inc"; return 0 ;;
        5:12) echo "Tier 1 Multichip Solutions"; return 0 ;;
        5:13) echo "CWRL Labs"; return 0 ;;
        5:14) echo "Teradici"; return 0 ;;
        5:15) echo "Gigaram, Inc."; return 0 ;;
        5:16) echo "g2 Microsystems"; return 0 ;;
        5:17) echo "PowerFlash Semiconductor"; return 0 ;;
        5:18) echo "P.A. Semi, Inc."; return 0 ;;
        5:19) echo "NovaTech Solutions, S.A."; return 0 ;;
        5:20) echo "c2 Microsystems, Inc."; return 0 ;;
        5:21) echo "Level5 Networks"; return 0 ;;
        5:22) echo "COS Memory AG"; return 0 ;;
        5:23) echo "Innovasic Semiconductor"; return 0 ;;
        5:24) echo "02IC Co. Ltd"; return 0 ;;
        5:25) echo "Tabula, Inc."; return 0 ;;
        5:26) echo "Crucial Technology"; return 0 ;;
        5:27) echo "Chelsio Communications"; return 0 ;;
        5:28) echo "Solarflare Communications"; return 0 ;;
        5:29) echo "Xambala Inc."; return 0 ;;
        5:30) echo "EADS Astrium"; return 0 ;;
        5:31) echo "Terra Semiconductor Inc. (former ATO Semicon Co. Ltd.)"; return 0 ;;
        5:32) echo "Imaging Works, Inc."; return 0 ;;
        5:33) echo "Astute Networks, Inc."; return 0 ;;
        5:34) echo "Tzero"; return 0 ;;
        5:35) echo "Emulex"; return 0 ;;
        5:36) echo "Power-One"; return 0 ;;
        5:37) echo "Pulse~LINK Inc."; return 0 ;;
        5:38) echo "Hon Hai Precision Industry"; return 0 ;;
        5:39) echo "White Rock Networks Inc."; return 0 ;;
        5:40) echo "Telegent Systems USA, Inc."; return 0 ;;
        5:41) echo "Atrua Technologies, Inc."; return 0 ;;
        5:42) echo "Acbel Polytech Inc."; return 0 ;;
        5:43) echo "eRide Inc."; return 0 ;;
        5:44) echo "ULi Electronics Inc."; return 0 ;;
        5:45) echo "Magnum Semiconductor Inc."; return 0 ;;
        5:46) echo "neoOne Technology, Inc."; return 0 ;;
        5:47) echo "Connex Technology, Inc."; return 0 ;;
        5:48) echo "Stream Processors, Inc."; return 0 ;;
        5:49) echo "Focus Enhancements"; return 0 ;;
        5:50) echo "Telecis Wireless, Inc."; return 0 ;;
        5:51) echo "uNav Microelectronics"; return 0 ;;
        5:52) echo "Tarari, Inc."; return 0 ;;
        5:53) echo "Ambric, Inc."; return 0 ;;
        5:54) echo "Newport Media, Inc."; return 0 ;;
        5:55) echo "VMTS"; return 0 ;;
        5:56) echo "Enuclia Semiconductor, Inc."; return 0 ;;
        5:57) echo "Virtium Technology Inc."; return 0 ;;
        5:58) echo "Solid State System Co., Ltd."; return 0 ;;
        5:59) echo "Kian Tech LLC"; return 0 ;;
        5:60) echo "Artimi"; return 0 ;;
        5:61) echo "Power Quotient International"; return 0 ;;
        5:62) echo "Avago Technologies"; return 0 ;;
        5:63) echo "ADTechnology"; return 0 ;;
        5:64) echo "Sigma Designs"; return 0 ;;
        5:65) echo "SiCortex, Inc."; return 0 ;;
        5:66) echo "Ventura Technology Group"; return 0 ;;
        5:67) echo "eASIC"; return 0 ;;
        5:68) echo "M.H.S. SAS"; return 0 ;;
        5:69) echo "Micro Star International"; return 0 ;;
        5:70) echo "Rapport Inc."; return 0 ;;
        5:71) echo "Makway International"; return 0 ;;
        5:72) echo "Broad Reach Engineering Co."; return 0 ;;
        5:73) echo "Semiconductor Mfg Intl Corp"; return 0 ;;
        5:74) echo "SiConnect"; return 0 ;;
        5:75) echo "FCI USA Inc."; return 0 ;;
        5:76) echo "Validity Sensors"; return 0 ;;
        5:77) echo "Coney Technology Co. Ltd."; return 0 ;;
        5:78) echo "Spans Logic"; return 0 ;;
        5:79) echo "Neterion Inc."; return 0 ;;
        5:80) echo "Qimonda"; return 0 ;;
        5:81) echo "New Japan Radio Co. Ltd."; return 0 ;;
        5:82) echo "Velogix"; return 0 ;;
        5:83) echo "Montalvo Systems"; return 0 ;;
        5:84) echo "iVivity Inc."; return 0 ;;
        5:85) echo "Walton Chaintech"; return 0 ;;
        5:86) echo "AENEON"; return 0 ;;
        5:87) echo "Lorom Industrial Co. Ltd."; return 0 ;;
        5:88) echo "Radiospire Networks"; return 0 ;;
        5:89) echo "Sensio Technologies, Inc."; return 0 ;;
        5:90) echo "Nethra Imaging"; return 0 ;;
        5:91) echo "Hexon Technology Pte Ltd"; return 0 ;;
        5:92) echo "CompuStocx (CSX)"; return 0 ;;
        5:93) echo "Methode Electronics, Inc."; return 0 ;;
        5:94) echo "Connect One Ltd."; return 0 ;;
        5:95) echo "Opulan Technologies"; return 0 ;;
        5:96) echo "Septentrio NV"; return 0 ;;
        5:97) echo "Goldenmars Technology Inc."; return 0 ;;
        5:98) echo "Kreton Corporation"; return 0 ;;
        5:99) echo "Cochlear Ltd."; return 0 ;;
        5:100) echo "Altair Semiconductor"; return 0 ;;
        5:101) echo "NetEffect, Inc."; return 0 ;;
        5:102) echo "Spansion, Inc."; return 0 ;;
        5:103) echo "Taiwan Semiconductor Mfg"; return 0 ;;
        5:104) echo "Emphany Systems Inc."; return 0 ;;
        5:105) echo "ApaceWave Technologies"; return 0 ;;
        5:106) echo "Mobilygen Corporation"; return 0 ;;
        5:107) echo "Tego"; return 0 ;;
        5:108) echo "Cswitch Corporation"; return 0 ;;
        5:109) echo "Haier (Beijing) IC Design Co."; return 0 ;;
        5:110) echo "MetaRAM"; return 0 ;;
        5:111) echo "Axel Electronics Co. Ltd."; return 0 ;;
        5:112) echo "Tilera Corporation"; return 0 ;;
        5:113) echo "Aquantia"; return 0 ;;
        5:114) echo "Vivace Semiconductor"; return 0 ;;
        5:115) echo "Redpine Signals"; return 0 ;;
        5:116) echo "Octalica"; return 0 ;;
        5:117) echo "InterDigital Communications"; return 0 ;;
        5:118) echo "Avant Technology"; return 0 ;;
        5:119) echo "Asrock, Inc."; return 0 ;;
        5:120) echo "Availink"; return 0 ;;
        5:121) echo "Quartics, Inc."; return 0 ;;
        5:122) echo "Element CXI"; return 0 ;;
        5:123) echo "Innovaciones Microelectronicas"; return 0 ;;
        5:124) echo "VeriSilicon Microelectronics"; return 0 ;;
        5:125) echo "W5 Networks"; return 0 ;;
        6:0) echo "MOVEKING"; return 0 ;;
        6:1) echo "Mavrix Technology, Inc."; return 0 ;;
        6:2) echo "CellGuide Ltd."; return 0 ;;
        6:3) echo "Faraday Technology"; return 0 ;;
        6:4) echo "Diablo Technologies, Inc."; return 0 ;;
        6:5) echo "Jennic"; return 0 ;;
        6:6) echo "Octasic"; return 0 ;;
        6:7) echo "Molex Incorporated"; return 0 ;;
        6:8) echo "3Leaf Networks"; return 0 ;;
        6:9) echo "Bright Micron Technology"; return 0 ;;
        6:10) echo "Netxen"; return 0 ;;
        6:11) echo "NextWave Broadband Inc."; return 0 ;;
        6:12) echo "DisplayLink"; return 0 ;;
        6:13) echo "ZMOS Technology"; return 0 ;;
        6:14) echo "Tec-Hill"; return 0 ;;
        6:15) echo "Multigig, Inc."; return 0 ;;
        6:16) echo "Amimon"; return 0 ;;
        6:17) echo "Euphonic Technologies, Inc."; return 0 ;;
        6:18) echo "BRN Phoenix"; return 0 ;;
        6:19) echo "InSilica"; return 0 ;;
        6:20) echo "Ember Corporation"; return 0 ;;
        6:21) echo "Avexir Technologies Corporation"; return 0 ;;
        6:22) echo "Echelon Corporation"; return 0 ;;
        6:23) echo "Edgewater Computer Systems"; return 0 ;;
        6:24) echo "XMOS Semiconductor Ltd."; return 0 ;;
        6:25) echo "GENUSION, Inc."; return 0 ;;
        6:26) echo "Memory Corp NV"; return 0 ;;
        6:27) echo "SiliconBlue Technologies"; return 0 ;;
        6:28) echo "Rambus Inc."; return 0 ;;
        6:29) echo "Andes Technology Corporation"; return 0 ;;
        6:30) echo "Coronis Systems"; return 0 ;;
        6:31) echo "Achronix Semiconductor"; return 0 ;;
        6:32) echo "Siano Mobile Silicon Ltd."; return 0 ;;
        6:33) echo "Semtech Corporation"; return 0 ;;
        6:34) echo "Pixelworks Inc."; return 0 ;;
        6:35) echo "Gaisler Research AB"; return 0 ;;
        6:36) echo "Teranetics"; return 0 ;;
        6:37) echo "Toppan Printing Co. Ltd."; return 0 ;;
        6:38) echo "Kingxcon"; return 0 ;;
        6:39) echo "Silicon Integrated Systems"; return 0 ;;
        6:40) echo "I-O Data Device, Inc."; return 0 ;;
        6:41) echo "NDS Americas Inc."; return 0 ;;
        6:42) echo "Solomon Systech Limited"; return 0 ;;
        6:43) echo "On Demand Microelectronics"; return 0 ;;
        6:44) echo "Amicus Wireless Inc."; return 0 ;;
        6:45) echo "SMARDTV SNC"; return 0 ;;
        6:46) echo "Comsys Communication Ltd."; return 0 ;;
        6:47) echo "Movidia Ltd."; return 0 ;;
        6:48) echo "Javad GNSS, Inc."; return 0 ;;
        6:49) echo "Montage Technology Group"; return 0 ;;
        6:50) echo "Trident Microsystems"; return 0 ;;
        6:51) echo "Super Talent"; return 0 ;;
        6:52) echo "Optichron, Inc."; return 0 ;;
        6:53) echo "Future Waves UK Ltd."; return 0 ;;
        6:54) echo "SiBEAM, Inc."; return 0 ;;
        6:55) echo "Inicore, Inc."; return 0 ;;
        6:56) echo "Virident Systems"; return 0 ;;
        6:57) echo "M2000, Inc."; return 0 ;;
        6:58) echo "ZeroG Wireless, Inc."; return 0 ;;
        6:59) echo "Gingle Technology Co. Ltd."; return 0 ;;
        6:60) echo "Space Micro Inc."; return 0 ;;
        6:61) echo "Wilocity"; return 0 ;;
        6:62) echo "Novafora, Inc."; return 0 ;;
        6:63) echo "iKoa Corporation"; return 0 ;;
        6:64) echo "ASint Technology"; return 0 ;;
        6:65) echo "Ramtron"; return 0 ;;
        6:66) echo "Plato Networks Inc."; return 0 ;;
        6:67) echo "IPtronics AS"; return 0 ;;
        6:68) echo "Infinite-Memories"; return 0 ;;
        6:69) echo "Parade Technologies Inc."; return 0 ;;
        6:70) echo "Dune Networks"; return 0 ;;
        6:71) echo "GigaDevice Semiconductor"; return 0 ;;
        6:72) echo "Modu Ltd."; return 0 ;;
        6:73) echo "CEITEC"; return 0 ;;
        6:74) echo "Northrop Grumman"; return 0 ;;
        6:75) echo "XRONET Corporation"; return 0 ;;
        6:76) echo "Sicon Semiconductor AB"; return 0 ;;
        6:77) echo "Atla Electronics Co. Ltd."; return 0 ;;
        6:78) echo "TOPRAM Technology"; return 0 ;;
        6:79) echo "Silego Technology Inc."; return 0 ;;
        6:80) echo "Kinglife"; return 0 ;;
        6:81) echo "Ability Industries Ltd."; return 0 ;;
        6:82) echo "Silicon Power Computer & Communications"; return 0 ;;
        6:83) echo "Augusta Technology, Inc."; return 0 ;;
        6:84) echo "Nantronics Semiconductors"; return 0 ;;
        6:85) echo "Hilscher Gesellschaft"; return 0 ;;
        6:86) echo "Quixant Ltd."; return 0 ;;
        6:87) echo "Percello Ltd."; return 0 ;;
        6:88) echo "NextIO Inc."; return 0 ;;
        6:89) echo "Scanimetrics Inc."; return 0 ;;
        6:90) echo "FS-Semi Company Ltd."; return 0 ;;
        6:91) echo "Infinera Corporation"; return 0 ;;
        6:92) echo "SandForce Inc."; return 0 ;;
        6:93) echo "Lexar Media"; return 0 ;;
        6:94) echo "Teradyne Inc."; return 0 ;;
        6:95) echo "Memory Exchange Corp."; return 0 ;;
        6:96) echo "Suzhou Smartek Electronics"; return 0 ;;
        6:97) echo "Avantium Corporation"; return 0 ;;
        6:98) echo "ATP Electronics Inc."; return 0 ;;
        6:99) echo "Valens Semiconductor Ltd"; return 0 ;;
        6:100) echo "Agate Logic, Inc."; return 0 ;;
        6:101) echo "Netronome"; return 0 ;;
        6:102) echo "Zenverge, Inc."; return 0 ;;
        6:103) echo "N-trig Ltd"; return 0 ;;
        6:104) echo "SanMax Technologies Inc."; return 0 ;;
        6:105) echo "Contour Semiconductor Inc."; return 0 ;;
        6:106) echo "TwinMOS"; return 0 ;;
        6:107) echo "Silicon Systems, Inc."; return 0 ;;
        6:108) echo "V-Color Technology Inc."; return 0 ;;
        6:109) echo "Certicom Corporation"; return 0 ;;
        6:110) echo "JSC ICC Milandr"; return 0 ;;
        6:111) echo "PhotoFast Global Inc."; return 0 ;;
        6:112) echo "InnoDisk Corporation"; return 0 ;;
        6:113) echo "Muscle Power"; return 0 ;;
        6:114) echo "Energy Micro"; return 0 ;;
        6:115) echo "Innofidei"; return 0 ;;
        6:116) echo "CopperGate Communications"; return 0 ;;
        6:117) echo "Holtek Semiconductor Inc."; return 0 ;;
        6:118) echo "Myson Century, Inc."; return 0 ;;
        6:119) echo "FIDELIX"; return 0 ;;
        6:120) echo "Red Digital Cinema"; return 0 ;;
        6:121) echo "Densbits Technology"; return 0 ;;
        6:122) echo "Zempro"; return 0 ;;
        6:123) echo "MoSys"; return 0 ;;
        6:124) echo "Provigent"; return 0 ;;
        6:125) echo "Triad Semiconductor, Inc."; return 0 ;;
        7:0) echo "Siklu Communication Ltd."; return 0 ;;
        7:1) echo "A Force Manufacturing Ltd."; return 0 ;;
        7:2) echo "Strontium"; return 0 ;;
        7:3) echo "ALi Corp (former Abilis Systems)"; return 0 ;;
        7:4) echo "Siglead, Inc."; return 0 ;;
        7:5) echo "Ubicom, Inc."; return 0 ;;
        7:6) echo "Unifosa Corporation"; return 0 ;;
        7:7) echo "Stretch, Inc."; return 0 ;;
        7:8) echo "Lantiq Deutschland GmbH"; return 0 ;;
        7:9) echo "Visipro"; return 0 ;;
        7:10) echo "EKMemory"; return 0 ;;
        7:11) echo "Microelectronics Institute ZTE"; return 0 ;;
        7:12) echo "u-blox AG (former Cognovo Ltd)"; return 0 ;;
        7:13) echo "Carry Technology Co. Ltd."; return 0 ;;
        7:14) echo "Nokia"; return 0 ;;
        7:15) echo "King Tiger Technology"; return 0 ;;
        7:16) echo "Sierra Wireless"; return 0 ;;
        7:17) echo "HT Micron"; return 0 ;;
        7:18) echo "Albatron Technology Co. Ltd."; return 0 ;;
        7:19) echo "Leica Geosystems AG"; return 0 ;;
        7:20) echo "BroadLight"; return 0 ;;
        7:21) echo "AEXEA"; return 0 ;;
        7:22) echo "ClariPhy Communications, Inc."; return 0 ;;
        7:23) echo "Green Plug"; return 0 ;;
        7:24) echo "Design Art Networks"; return 0 ;;
        7:25) echo "Mach Xtreme Technology Ltd."; return 0 ;;
        7:26) echo "ATO Solutions Co. Ltd."; return 0 ;;
        7:27) echo "Ramsta"; return 0 ;;
        7:28) echo "Greenliant Systems, Ltd."; return 0 ;;
        7:29) echo "Teikon"; return 0 ;;
        7:30) echo "Antec Hadron"; return 0 ;;
        7:31) echo "NavCom Technology, Inc."; return 0 ;;
        7:32) echo "Shanghai Fudan Microelectronics"; return 0 ;;
        7:33) echo "Calxeda, Inc."; return 0 ;;
        7:34) echo "JSC EDC Electronics"; return 0 ;;
        7:35) echo "Kandit Technology Co. Ltd."; return 0 ;;
        7:36) echo "Ramos Technology"; return 0 ;;
        7:37) echo "Goldenmars Technology"; return 0 ;;
        7:38) echo "XeL Technology Inc."; return 0 ;;
        7:39) echo "Newzone Corporation"; return 0 ;;
        7:40) echo "ShenZhen MercyPower Tech"; return 0 ;;
        7:41) echo "Nanjing Yihuo Technology"; return 0 ;;
        7:42) echo "Nethra Imaging Inc."; return 0 ;;
        7:43) echo "SiTel Semiconductor BV"; return 0 ;;
        7:44) echo "SolidGear Corporation"; return 0 ;;
        7:45) echo "Topower Computer Ind Co Ltd."; return 0 ;;
        7:46) echo "Wilocity"; return 0 ;;
        7:47) echo "Profichip GmbH"; return 0 ;;
        7:48) echo "Gerad Technologies"; return 0 ;;
        7:49) echo "Ritek Corporation"; return 0 ;;
        7:50) echo "Gomos Technology Limited"; return 0 ;;
        7:51) echo "Memoright Corporation"; return 0 ;;
        7:52) echo "D-Broad, Inc."; return 0 ;;
        7:53) echo "HiSilicon Technologies"; return 0 ;;
        7:54) echo "Syndiant Inc."; return 0 ;;
        7:55) echo "Enverv Inc."; return 0 ;;
        7:56) echo "Cognex"; return 0 ;;
        7:57) echo "Xinnova Technology Inc."; return 0 ;;
        7:58) echo "Ultron AG"; return 0 ;;
        7:59) echo "Concord Idea Corporation"; return 0 ;;
        7:60) echo "AIM Corporation"; return 0 ;;
        7:61) echo "Lifetime Memory Products"; return 0 ;;
        7:62) echo "Ramsway"; return 0 ;;
        7:63) echo "Recore Systems BV"; return 0 ;;
        7:64) echo "Haotian Jinshibo Science Tech"; return 0 ;;
        7:65) echo "Being Advanced Memory"; return 0 ;;
        7:66) echo "Adesto Technologies"; return 0 ;;
        7:67) echo "Giantec Semiconductor, Inc."; return 0 ;;
        7:68) echo "HMD Electronics AG"; return 0 ;;
        7:69) echo "Gloway International (HK)"; return 0 ;;
        7:70) echo "Kingcore"; return 0 ;;
        7:71) echo "Anucell Technology Holding"; return 0 ;;
        7:72) echo "Accord Software & Systems Pvt. Ltd."; return 0 ;;
        7:73) echo "Active-Semi Inc."; return 0 ;;
        7:74) echo "Denso Corporation"; return 0 ;;
        7:75) echo "TLSI Inc."; return 0 ;;
        7:76) echo "Shenzhen Daling Electronic Co. Ltd."; return 0 ;;
        7:77) echo "Mustang"; return 0 ;;
        7:78) echo "Orca Systems"; return 0 ;;
        7:79) echo "Passif Semiconductor"; return 0 ;;
        7:80) echo "GigaDevice Semiconductor (Beijing) Inc."; return 0 ;;
        7:81) echo "Memphis Electronic"; return 0 ;;
        7:82) echo "Beckhoff Automation GmbH"; return 0 ;;
        7:83) echo "Harmony Semiconductor Corp (former ProPlus Design Solutions)"; return 0 ;;
        7:84) echo "Air Computers SRL"; return 0 ;;
        7:85) echo "TMT Memory"; return 0 ;;
        7:86) echo "Eorex Corporation"; return 0 ;;
        7:87) echo "Xingtera"; return 0 ;;
        7:88) echo "Netsol"; return 0 ;;
        7:89) echo "Bestdon Technology Co. Ltd."; return 0 ;;
        7:90) echo "Baysand Inc."; return 0 ;;
        7:91) echo "Uroad Technology Co. Ltd. (former Triple Grow Industrial Ltd.)"; return 0 ;;
        7:92) echo "Wilk Elektronik S.A."; return 0 ;;
        7:93) echo "AAI"; return 0 ;;
        7:94) echo "Harman"; return 0 ;;
        7:95) echo "Berg Microelectronics Inc."; return 0 ;;
        7:96) echo "ASSIA, Inc."; return 0 ;;
        7:97) echo "Visiontek Products LLC"; return 0 ;;
        7:98) echo "OCMEMORY"; return 0 ;;
        7:99) echo "Welink Solution Inc."; return 0 ;;
        7:100) echo "Shark Gaming"; return 0 ;;
        7:101) echo "Avalanche Technology"; return 0 ;;
        7:102) echo "R&D Center ELVEES OJSC"; return 0 ;;
        7:103) echo "KingboMars Technology Co. Ltd."; return 0 ;;
        7:104) echo "High Bridge Solutions Industria Eletronica"; return 0 ;;
        7:105) echo "Transcend Technology Co. Ltd."; return 0 ;;
        7:106) echo "Everspin Technologies"; return 0 ;;
        7:107) echo "Hon-Hai Precision"; return 0 ;;
        7:108) echo "Smart Storage Systems"; return 0 ;;
        7:109) echo "Toumaz Group"; return 0 ;;
        7:110) echo "Zentel Electronics Corporation"; return 0 ;;
        7:111) echo "Panram International Corporation"; return 0 ;;
        7:112) echo "Silicon Space Technology"; return 0 ;;
        7:113) echo "LITE-ON IT Corporation"; return 0 ;;
        7:114) echo "Inuitive"; return 0 ;;
        7:115) echo "HMicro"; return 0 ;;
        7:116) echo "BittWare Inc."; return 0 ;;
        7:117) echo "GLOBALFOUNDRIES"; return 0 ;;
        7:118) echo "ACPI Digital Co. Ltd"; return 0 ;;
        7:119) echo "Annapurna Labs"; return 0 ;;
        7:120) echo "AcSiP Technology Corporation"; return 0 ;;
        7:121) echo "Idea! Electronic Systems"; return 0 ;;
        7:122) echo "Gowe Technology Co. Ltd"; return 0 ;;
        7:123) echo "Hermes Testing Solutions Inc."; return 0 ;;
        7:124) echo "Positivo BGH"; return 0 ;;
        7:125) echo "Intelligence Silicon Technology"; return 0 ;;
        8:0) echo "3D PLUS"; return 0 ;;
        8:1) echo "Diehl Aerospace"; return 0 ;;
        8:2) echo "Fairchild"; return 0 ;;
        8:3) echo "Mercury Systems"; return 0 ;;
        8:4) echo "Sonics Inc."; return 0 ;;
        8:5) echo "Emerson Automation Solutions (former ICC/GE Intelligent Platforms)"; return 0 ;;
        8:6) echo "Shenzhen Jinge Information Co. Ltd"; return 0 ;;
        8:7) echo "SCWW"; return 0 ;;
        8:8) echo "Silicon Motion Inc."; return 0 ;;
        8:9) echo "Anurag"; return 0 ;;
        8:10) echo "King Kong"; return 0 ;;
        8:11) echo "FROM30 Co. Ltd"; return 0 ;;
        8:12) echo "Gowin Semiconductor Corp"; return 0 ;;
        8:13) echo "Fremont Micro Devices Ltd"; return 0 ;;
        8:14) echo "Ericsson Modems"; return 0 ;;
        8:15) echo "Exelis"; return 0 ;;
        8:16) echo "Satixfy Ltd"; return 0 ;;
        8:17) echo "Galaxy Microsystems Ltd"; return 0 ;;
        8:18) echo "Gloway International Co. Ltd"; return 0 ;;
        8:19) echo "Lab"; return 0 ;;
        8:20) echo "Smart Energy Instruments"; return 0 ;;
        8:21) echo "Approved Memory Corporation"; return 0 ;;
        8:22) echo "Axell Corporation"; return 0 ;;
        8:23) echo "Essencore Limited (former ISD Technology Limited)"; return 0 ;;
        8:24) echo "Phytium"; return 0 ;;
        8:25) echo "Xi’an UniIC Semiconductors Co Ltd (former Xi'an SinoChip Semiconductor)"; return 0 ;;
        8:26) echo "Ambiq Micro"; return 0 ;;
        8:27) echo "eveRAM Technology Inc."; return 0 ;;
        8:28) echo "Infomax"; return 0 ;;
        8:29) echo "Butterfly Network Inc."; return 0 ;;
        8:30) echo "Shenzhen City Gcai Electronics"; return 0 ;;
        8:31) echo "Stack Devices Corporation"; return 0 ;;
        8:32) echo "ADK Media Group"; return 0 ;;
        8:33) echo "TSP Global Co. Ltd"; return 0 ;;
        8:34) echo "HighX"; return 0 ;;
        8:35) echo "Shenzhen Elicks Technology"; return 0 ;;
        8:36) echo "ISSI/Chingis"; return 0 ;;
        8:37) echo "Google Inc."; return 0 ;;
        8:38) echo "Dasima International Development"; return 0 ;;
        8:39) echo "Leahkinn Technology Limited"; return 0 ;;
        8:40) echo "HIMA Paul Hildebrandt GmbH Co KG"; return 0 ;;
        8:41) echo "Keysight Technologies"; return 0 ;;
        8:42) echo "Techcomp International (Fastable)"; return 0 ;;
        8:43) echo "Ancore Technology Corporation"; return 0 ;;
        8:44) echo "Nuvoton"; return 0 ;;
        8:45) echo "Korea Uhbele International Group Ltd"; return 0 ;;
        8:46) echo "Ikegami Tsushinki Co. Ltd"; return 0 ;;
        8:47) echo "RelChip Inc."; return 0 ;;
        8:48) echo "Baikal Electronics"; return 0 ;;
        8:49) echo "Nemostech Inc."; return 0 ;;
        8:50) echo "Memorysolution GmbH"; return 0 ;;
        8:51) echo "Silicon Integrated Systems Corporation"; return 0 ;;
        8:52) echo "Xiede"; return 0 ;;
        8:53) echo "BRC (former Multilaser Components)"; return 0 ;;
        8:54) echo "Flash Chi"; return 0 ;;
        8:55) echo "Jone"; return 0 ;;
        8:56) echo "GCT Semiconductor Inc."; return 0 ;;
        8:57) echo "Hong Kong Zetta Device Technology"; return 0 ;;
        8:58) echo "Unimemory Technology(s) Pte Ltd"; return 0 ;;
        8:59) echo "Cuso"; return 0 ;;
        8:60) echo "Kuso"; return 0 ;;
        8:61) echo "Uniquify Inc."; return 0 ;;
        8:62) echo "Skymedi Corporation"; return 0 ;;
        8:63) echo "Core Chance Co. Ltd"; return 0 ;;
        8:64) echo "Tekism Co. Ltd"; return 0 ;;
        8:65) echo "Seagate Technology PLC"; return 0 ;;
        8:66) echo "Hong Kong Gaia Group Co. Limited"; return 0 ;;
        8:67) echo "Gigacom Semiconductor LLC"; return 0 ;;
        8:68) echo "V2 Technologies"; return 0 ;;
        8:69) echo "TLi"; return 0 ;;
        8:70) echo "Neotion"; return 0 ;;
        8:71) echo "Lenovo"; return 0 ;;
        8:72) echo "Shenzhen Zhongteng Electronic Corp. Ltd"; return 0 ;;
        8:73) echo "Compound Photonics"; return 0 ;;
        8:74) echo "In2H2 Inc (former Cognimem Technologies Inc)"; return 0 ;;
        8:75) echo "Shenzhen Pango Microsystems Co. Ltd"; return 0 ;;
        8:76) echo "Vasekey"; return 0 ;;
        8:77) echo "Cal-Comp Industria de Semicondutores"; return 0 ;;
        8:78) echo "Eyenix Co. Ltd"; return 0 ;;
        8:79) echo "Heoriady"; return 0 ;;
        8:80) echo "Accelerated Memory Production Inc."; return 0 ;;
        8:81) echo "INVECAS Inc."; return 0 ;;
        8:82) echo "AP Memory"; return 0 ;;
        8:83) echo "Douqi Technology"; return 0 ;;
        8:84) echo "Etron Technology Inc."; return 0 ;;
        8:85) echo "Indie Semiconductor"; return 0 ;;
        8:86) echo "Socionext Inc."; return 0 ;;
        8:87) echo "HGST"; return 0 ;;
        8:88) echo "EVGA"; return 0 ;;
        8:89) echo "Audience Inc."; return 0 ;;
        8:90) echo "EpicGear"; return 0 ;;
        8:91) echo "Vitesse Enterprise Co."; return 0 ;;
        8:92) echo "Foxtronn International Corporation"; return 0 ;;
        8:93) echo "Bretelon Inc."; return 0 ;;
        8:94) echo "Graphcore"; return 0 ;;
        8:95) echo "Eoplex Inc"; return 0 ;;
        8:96) echo "MaxLinear Inc"; return 0 ;;
        8:97) echo "ETA Devices"; return 0 ;;
        8:98) echo "LOKI"; return 0 ;;
        8:99) echo "IMS Electronics Co Ltd"; return 0 ;;
        8:100) echo "Dosilicon Co Ltd"; return 0 ;;
        8:101) echo "Dolphin Integration"; return 0 ;;
        8:102) echo "Shenzhen Mic Electronics Technolog"; return 0 ;;
        8:103) echo "Boya Microelectronics Inc"; return 0 ;;
        8:104) echo "Geniachip (Roche)"; return 0 ;;
        8:105) echo "Axign"; return 0 ;;
        8:106) echo "Kingred Electronic Technology Ltd"; return 0 ;;
        8:107) echo "Chao Yue Zhuo Computer Business Dept."; return 0 ;;
        8:108) echo "Guangzhou Si Nuo Electronic Technology."; return 0 ;;
        8:109) echo "Crocus Technology Inc"; return 0 ;;
        8:110) echo "Creative Chips GmbH"; return 0 ;;
        8:111) echo "GE Aviation Systems LLC."; return 0 ;;
        8:112) echo "Asgard"; return 0 ;;
        8:113) echo "Good Wealth Technology Ltd"; return 0 ;;
        8:114) echo "TriCor Technologies"; return 0 ;;
        8:115) echo "Nova-Systems GmbH"; return 0 ;;
        8:116) echo "JUHOR"; return 0 ;;
        8:117) echo "Zhuhai Douke Commerce Co Ltd"; return 0 ;;
        8:118) echo "DSL Memory"; return 0 ;;
        8:119) echo "Anvo-Systems Dresden GmbH"; return 0 ;;
        8:120) echo "Realtek"; return 0 ;;
        8:121) echo "AltoBeam"; return 0 ;;
        8:122) echo "Wave Computing"; return 0 ;;
        8:123) echo "Beijing TrustNet Technology Co Ltd"; return 0 ;;
        8:124) echo "Innovium Inc"; return 0 ;;
        8:125) echo "Starsway Technology Limited"; return 0 ;;
        9:0) echo "Weltronics Co LTD"; return 0 ;;
        9:1) echo "VMware Inc"; return 0 ;;
        9:2) echo "Hewlett Packard Enterprise"; return 0 ;;
        9:3) echo "INTENSO"; return 0 ;;
        9:4) echo "Puya Semiconductor"; return 0 ;;
        9:5) echo "MEMORFI"; return 0 ;;
        9:6) echo "MSC Technologies GmbH"; return 0 ;;
        9:7) echo "Txrui"; return 0 ;;
        9:8) echo "SiFive Inc"; return 0 ;;
        9:9) echo "Spreadtrum Communications"; return 0 ;;
        9:10) echo "XTX Technology Limited"; return 0 ;;
        9:11) echo "UMAX Technology"; return 0 ;;
        9:12) echo "Shenzhen Yong Sheng Technology"; return 0 ;;
        9:13) echo "SNOAMOO (Shenzhen Kai Zhuo Yue)"; return 0 ;;
        9:14) echo "Daten Tecnologia LTDA"; return 0 ;;
        9:15) echo "Shenzhen XinRuiYan Electronics"; return 0 ;;
        9:16) echo "Eta Compute"; return 0 ;;
        9:17) echo "Energous"; return 0 ;;
        9:18) echo "Raspberry Pi Trading Ltd"; return 0 ;;
        9:19) echo "Shenzhen Chixingzhe Tech Co Ltd"; return 0 ;;
        9:20) echo "Silicon Mobility"; return 0 ;;
        9:21) echo "IQ-Analog Corporation"; return 0 ;;
        9:22) echo "Uhnder Inc"; return 0 ;;
        9:23) echo "Impinj"; return 0 ;;
        9:24) echo "DEPO Computers"; return 0 ;;
        9:25) echo "Nespeed Sysems"; return 0 ;;
        9:26) echo "Yangtze Memory Technologies Co Ltd"; return 0 ;;
        9:27) echo "MemxPro Inc"; return 0 ;;
        9:28) echo "Tammuz Co Ltd"; return 0 ;;
        9:29) echo "Allwinner Technology"; return 0 ;;
        9:30) echo "Shenzhen City Futian District Qing Xuan Tong Computer Trading Firm"; return 0 ;;
        9:31) echo "XMC"; return 0 ;;
        9:32) echo "Teclast"; return 0 ;;
        9:33) echo "Maxsun"; return 0 ;;
        9:34) echo "Haiguang Integrated Circuit Design"; return 0 ;;
        9:35) echo "RamCENTER Technology"; return 0 ;;
        9:36) echo "Phison Electronics Corporation"; return 0 ;;
        9:37) echo "Guizhou Huaxintong Semi-Conductor"; return 0 ;;
        9:38) echo "Network Intelligence"; return 0 ;;
        9:39) echo "Continental Technology (Holdings)"; return 0 ;;
        9:40) echo "Guangzhou Huayan Suning Electronic"; return 0 ;;
        9:41) echo "Guangzhou Zhouji Electronic Co Ltd"; return 0 ;;
        9:42) echo "Shenzhen Giant Hui Kang Tech Co Ltd"; return 0 ;;
        9:43) echo "Shenzhen Yilong Innovative Co Ltd"; return 0 ;;
        9:44) echo "Neo Forza"; return 0 ;;
        9:45) echo "Lyontek Inc"; return 0 ;;
        9:46) echo "Shanghai Kuxin Microelectronics Ltd"; return 0 ;;
        9:47) echo "Shenzhen Larix Technology Co Ltd"; return 0 ;;
        9:48) echo "Qbit Semiconductor Ltd"; return 0 ;;
        9:49) echo "Insignis Technology Corporation"; return 0 ;;
        9:50) echo "Lanson Memory Co Ltd"; return 0 ;;
        9:51) echo "Shenzhen Superway Electronics Co Ltd"; return 0 ;;
        9:52) echo "Canaan-Creative Co Ltd"; return 0 ;;
        9:53) echo "Black Diamond Memory"; return 0 ;;
        9:54) echo "Shenzhen City Parker Baking Electronics"; return 0 ;;
        9:55) echo "Shenzhen Baihong Technology Co Ltd"; return 0 ;;
        9:56) echo "GEO Semiconductors"; return 0 ;;
        9:57) echo "OCPC"; return 0 ;;
        9:58) echo "Artery Technology Co Ltd"; return 0 ;;
        9:59) echo "Jinyu"; return 0 ;;
        9:60) echo "ShenzhenYing Chi Technology Development"; return 0 ;;
        9:61) echo "Shenzhen Pengcheng Xin Technology"; return 0 ;;
        9:62) echo "Pegasus Semiconductor (Shanghai) Co"; return 0 ;;
        9:63) echo "Mythic Inc"; return 0 ;;
        9:64) echo "Elmos Semiconductor AG"; return 0 ;;
        9:65) echo "Kllisre"; return 0 ;;
        9:66) echo "Shenzhen Winconway Technology"; return 0 ;;
        9:67) echo "Shenzhen Xingmem Technology Corp"; return 0 ;;
        9:68) echo "Gold Key Technology Co Ltd"; return 0 ;;
        9:69) echo "Habana Labs Ltd"; return 0 ;;
        9:70) echo "Hoodisk Electronics Co Ltd"; return 0 ;;
        9:71) echo "SemsoTai (SZ) Technology Co Ltd"; return 0 ;;
        9:72) echo "OM Nanotech Pvt. Ltd"; return 0 ;;
        9:73) echo "Shenzhen Zhifeng Weiye Technology"; return 0 ;;
        9:74) echo "Xinshirui (Shenzhen) Electronics Co"; return 0 ;;
        9:75) echo "Guangzhou Zhong Hao Tian Electronic"; return 0 ;;
        9:76) echo "Shenzhen Longsys Electronics Co Ltd"; return 0 ;;
        9:77) echo "Deciso B.V."; return 0 ;;
        9:78) echo "Puya Semiconductor (Shenzhen)"; return 0 ;;
        9:79) echo "Shenzhen Veineda Technology Co Ltd"; return 0 ;;
        9:80) echo "Antec Memory"; return 0 ;;
        9:81) echo "Cortus SAS"; return 0 ;;
        9:82) echo "Dust Leopard"; return 0 ;;
        9:83) echo "MyWo AS"; return 0 ;;
        9:84) echo "J&A Information Inc"; return 0 ;;
        9:85) echo "Shenzhen JIEPEI Technology Co Ltd"; return 0 ;;
        9:86) echo "Heidelberg University"; return 0 ;;
        9:87) echo "Flexxon PTE Ltd"; return 0 ;;
        9:88) echo "Wiliot"; return 0 ;;
        9:89) echo "Raysun Electronics International Ltd"; return 0 ;;
        9:90) echo "Aquarius Production Company LLC"; return 0 ;;
        9:91) echo "MACNICA DHW LTDA"; return 0 ;;
        9:92) echo "Intelimem"; return 0 ;;
        9:93) echo "Zbit Semiconductor Inc"; return 0 ;;
        9:94) echo "Shenzhen Technology Co Ltd"; return 0 ;;
        9:95) echo "Signalchip"; return 0 ;;
        9:96) echo "Shenzen Recadata Storage Technology"; return 0 ;;
        9:97) echo "Hyundai Technology"; return 0 ;;
        9:98) echo "Shanghai Fudi Investment Development"; return 0 ;;
        9:99) echo "Aixi Technology"; return 0 ;;
        9:100) echo "Tecon MT"; return 0 ;;
        9:101) echo "Onda Electric Co Ltd"; return 0 ;;
        9:102) echo "Jinshen"; return 0 ;;
        9:103) echo "Kimtigo Semiconductor (HK) Limited"; return 0 ;;
        9:104) echo "IIT Madras"; return 0 ;;
        9:105) echo "Shenshan (Shenzhen) Electronic"; return 0 ;;
        9:106) echo "Hefei Core Storage Electronic Limited"; return 0 ;;
        9:107) echo "Colorful Technology Ltd"; return 0 ;;
        9:108) echo "Visenta (Xiamen) Technology Co Ltd"; return 0 ;;
        9:109) echo "Roa Logic BV"; return 0 ;;
        9:110) echo "NSITEXE Inc"; return 0 ;;
        9:111) echo "Hong Kong Hyunion Electronics"; return 0 ;;
        9:112) echo "ASK Technology Group Limited"; return 0 ;;
        9:113) echo "GIGA-BYTE Technology Co Ltd"; return 0 ;;
        9:114) echo "Terabyte Co Ltd"; return 0 ;;
        9:115) echo "Hyundai Inc"; return 0 ;;
        9:116) echo "EXCELERAM"; return 0 ;;
        9:117) echo "PsiKick"; return 0 ;;
        9:118) echo "Netac Technology Co Ltd"; return 0 ;;
        9:119) echo "PCCOOLER"; return 0 ;;
        9:120) echo "Jiangsu Huacun Electronic Technology"; return 0 ;;
        9:121) echo "Shenzhen Micro Innovation Industry"; return 0 ;;
        9:122) echo "Beijing Tongfang Microelectronics Co"; return 0 ;;
        9:123) echo "XZN Storage Technology"; return 0 ;;
        9:124) echo "ChipCraft Sp. z.o.o."; return 0 ;;
        9:125) echo "ALLFLASH Technology Limited"; return 0 ;;
        10:0) echo "Foerd Technology Co Ltd"; return 0 ;;
        10:1) echo "KingSpec"; return 0 ;;
        10:2) echo "Codasip GmbH"; return 0 ;;
        10:3) echo "SL Link Co Ltd"; return 0 ;;
        10:4) echo "Shenzhen Kefu Technology Co Limited"; return 0 ;;
        10:5) echo "Shenzhen ZST Electronics Technology"; return 0 ;;
        10:6) echo "Kyokuto Electronic Inc"; return 0 ;;
        10:7) echo "Warrior Technology"; return 0 ;;
        10:8) echo "TRINAMIC Motion Control GmbH & Co"; return 0 ;;
        10:9) echo "PixelDisplay Inc"; return 0 ;;
        10:10) echo "Shenzhen Futian District Bo Yueda Elec"; return 0 ;;
        10:11) echo "Richtek Power"; return 0 ;;
        10:12) echo "Shenzhen LianTeng Electronics Co Ltd"; return 0 ;;
        10:13) echo "AITC Memory"; return 0 ;;
        10:14) echo "UNIC Memory Technology Co Ltd"; return 0 ;;
        10:15) echo "Shenzhen Huafeng Science Technology"; return 0 ;;
        10:16) echo "CXMT (former Innotron Memory Co Ltd)"; return 0 ;;
        10:17) echo "Guangzhou Xinyi Heng Computer Trading Firm"; return 0 ;;
        10:18) echo "SambaNova Systems"; return 0 ;;
        10:19) echo "V-GEN"; return 0 ;;
        10:20) echo "Jump Trading"; return 0 ;;
        10:21) echo "Ampere Computing"; return 0 ;;
        10:22) echo "Shenzhen Zhongshi Technology Co Ltd"; return 0 ;;
        10:23) echo "Shenzhen Zhongtian Bozhong Technology"; return 0 ;;
        10:24) echo "Tri-Tech International"; return 0 ;;
        10:25) echo "Silicon Intergrated Systems Corporation"; return 0 ;;
        10:26) echo "Shenzhen HongDingChen Information"; return 0 ;;
        10:27) echo "Plexton Holdings Limited"; return 0 ;;
        10:28) echo "AMS (Jiangsu Advanced Memory Semi)"; return 0 ;;
        10:29) echo "Wuhan Jing Tian Interconnected Tech Co"; return 0 ;;
        10:30) echo "Axia Memory Technology"; return 0 ;;
        10:31) echo "Chipset Technology Holding Limited"; return 0 ;;
        10:32) echo "Shenzhen Xinshida Technology Co Ltd"; return 0 ;;
        10:33) echo "Shenzhen Chuangshifeida Technology"; return 0 ;;
        10:34) echo "Guangzhou MiaoYuanJi Technology"; return 0 ;;
        10:35) echo "ADVAN Inc"; return 0 ;;
        10:36) echo "Shenzhen Qianhai Weishengda Electronic Commerce Company Ltd"; return 0 ;;
        10:37) echo "Guangzhou Guang Xie Cheng Trading"; return 0 ;;
        10:38) echo "StarRam International Co Ltd"; return 0 ;;
        10:39) echo "Shen Zhen XinShenHua Tech Co Ltd"; return 0 ;;
        10:40) echo "UltraMemory Inc"; return 0 ;;
        10:41) echo "New Coastline Global Tech Industry Co"; return 0 ;;
        10:42) echo "Sinker"; return 0 ;;
        10:43) echo "Diamond"; return 0 ;;
        10:44) echo "PUSKILL"; return 0 ;;
        10:45) echo "Guangzhou Hao Jia Ye Technology Co"; return 0 ;;
        10:46) echo "Ming Xin Limited"; return 0 ;;
        10:47) echo "Barefoot Networks"; return 0 ;;
        10:48) echo "Biwin Semiconductor (HK) Co Ltd"; return 0 ;;
        10:49) echo "UD INFO Corporation"; return 0 ;;
        10:50) echo "Trek Technology (S) PTE Ltd"; return 0 ;;
        10:51) echo "Xiamen Kingblaze Technology Co Ltd"; return 0 ;;
        10:52) echo "Shenzhen Lomica Technology Co Ltd"; return 0 ;;
        10:53) echo "Nuclei System Technology Co Ltd"; return 0 ;;
        10:54) echo "Wuhan Xun Zhan Electronic Technology"; return 0 ;;
        10:55) echo "Shenzhen Ingacom Semiconductor Ltd"; return 0 ;;
        10:56) echo "Zotac Technology Ltd"; return 0 ;;
        10:57) echo "Foxline"; return 0 ;;
        10:58) echo "Shenzhen Farasia Science Technology"; return 0 ;;
        10:59) echo "Efinix Inc"; return 0 ;;
        10:60) echo "Hua Nan San Xian Technology Co Ltd"; return 0 ;;
        10:61) echo "Goldtech Electronics Co Ltd"; return 0 ;;
        10:62) echo "Shanghai Han Rong Microelectronics Co"; return 0 ;;
        10:63) echo "Shenzhen Zhongguang Yunhe Trading"; return 0 ;;
        10:64) echo "Smart Shine(QingDao) Microelectronics"; return 0 ;;
        10:65) echo "Thermaltake Technology Co Ltd"; return 0 ;;
        10:66) echo "Shenzhen O'Yang Maile Technology Ltd"; return 0 ;;
        10:67) echo "UPMEM"; return 0 ;;
        10:68) echo "Chun Well Technology Holding Limited"; return 0 ;;
        10:69) echo "Astera Labs Inc"; return 0 ;;
        10:70) echo "Winconway"; return 0 ;;
        10:71) echo "Advantech Co Ltd"; return 0 ;;
        10:72) echo "Chengdu Fengcai Electronic Technology"; return 0 ;;
        10:73) echo "The Boeing Company"; return 0 ;;
        10:74) echo "Blaize Inc"; return 0 ;;
        10:75) echo "Ramonster Technology Co Ltd"; return 0 ;;
        10:76) echo "Wuhan Naonongmai Technology Co Ltd"; return 0 ;;
        10:77) echo "Shenzhen Hui ShingTong Technology"; return 0 ;;
        10:78) echo "Yourlyon"; return 0 ;;
        10:79) echo "Fabu Technology"; return 0 ;;
        10:80) echo "Shenzhen Yikesheng Technology Co Ltd"; return 0 ;;
        10:81) echo "NOR-MEM"; return 0 ;;
        10:82) echo "Cervoz Co Ltd"; return 0 ;;
        10:83) echo "Bitmain Technologies Inc"; return 0 ;;
        10:84) echo "Facebook Inc"; return 0 ;;
        10:85) echo "Shenzhen Longsys Electronics Co Ltd"; return 0 ;;
        10:86) echo "Guangzhou Siye Electronic Technology"; return 0 ;;
        10:87) echo "Silergy"; return 0 ;;
        10:88) echo "Adamway"; return 0 ;;
        10:89) echo "PZG"; return 0 ;;
        10:90) echo "Shenzhen King Power Electronics"; return 0 ;;
        10:91) echo "Guangzhou ZiaoFu Tranding Co Ltd"; return 0 ;;
        10:92) echo "Shenzhen SKIHOTAR Semiconductor"; return 0 ;;
        10:93) echo "PulseRain Technology"; return 0 ;;
        10:94) echo "Seeker Technology Limited"; return 0 ;;
        10:95) echo "Shenzhen OSCOO Tech Co Ltd"; return 0 ;;
        10:96) echo "Shenzhen Yze Technology Co Ltd"; return 0 ;;
        10:97) echo "Shenzhen Jieshuo Electronic Commerce"; return 0 ;;
        10:98) echo "Gazda"; return 0 ;;
        10:99) echo "Hua Wei Technology Co Ltd"; return 0 ;;
        10:100) echo "Esperanto Technologies"; return 0 ;;
        10:101) echo "JinSheng Electronic (Shenzhen) Co Ltd"; return 0 ;;
        10:102) echo "Shenzhen Shi Bolunshuai Technology"; return 0 ;;
        10:103) echo "Shanghai Rei Zuan Information Tech"; return 0 ;;
        10:104) echo "Fraunhofer IIS"; return 0 ;;
        10:105) echo "Kandou Bus SA"; return 0 ;;
        10:106) echo "Acer"; return 0 ;;
        10:107) echo "Artmem Technology Co Ltd"; return 0 ;;
        10:108) echo "Gstar Semiconductor Co Ltd"; return 0 ;;
        10:109) echo "ShineDisk"; return 0 ;;
        10:110) echo "Shenzhen CHN Technology Co Ltd"; return 0 ;;
        10:111) echo "UnionChip Semiconductor Co Ltd"; return 0 ;;
        10:112) echo "Tanbassh"; return 0 ;;
        10:113) echo "Shenzhen Tianyu Jieyun Intl Logistics"; return 0 ;;
        10:114) echo "MCLogic Inc"; return 0 ;;
        10:115) echo "Eorex Corporation"; return 0 ;;
        10:116) echo "Arm Technology (China) Co Ltd"; return 0 ;;
        10:117) echo "Lexar Co Limited"; return 0 ;;
        10:118) echo "QinetiQ Group PLC"; return 0 ;;
        10:119) echo "Exascend"; return 0 ;;
        10:120) echo "Hong Kong Hyunion Electronics Co Ltd"; return 0 ;;
        10:121) echo "Shenzhen Banghong Electronics Co Ltd"; return 0 ;;
        10:122) echo "MBit Wireless Inc"; return 0 ;;
        10:123) echo "Hex Five Security Inc"; return 0 ;;
        10:124) echo "ShenZhen Juhor Precision Tech Co Ltd"; return 0 ;;
        10:125) echo "Shenzhen Reeinno Technology Co Ltd"; return 0 ;;
        11:0) echo "ABIT Electronics (Shenzhen) Co Ltd"; return 0 ;;
        11:1) echo "Semidrive"; return 0 ;;
        11:2) echo "MyTek Electronics Corp"; return 0 ;;
        11:3) echo "Wxilicon Technology Co Ltd"; return 0 ;;
        11:4) echo "Shenzhen Meixin Electronics Ltd"; return 0 ;;
        11:5) echo "Ghost Wolf"; return 0 ;;
        11:6) echo "LiSion Technologies Inc"; return 0 ;;
        11:7) echo "Power Active Co Ltd"; return 0 ;;
        11:8) echo "Pioneer High Fidelity Taiwan Co. Ltd"; return 0 ;;
        11:9) echo "LuoSilk"; return 0 ;;
        11:10) echo "Shenzhen Chuangshifeida Technology"; return 0 ;;
        11:11) echo "Black Sesame Technologies Inc"; return 0 ;;
        11:12) echo "Jiangsu Xinsheng Intelligent Technology"; return 0 ;;
        11:13) echo "MLOONG"; return 0 ;;
        11:14) echo "Quadratica LLC"; return 0 ;;
        11:15) echo "Anpec Electronics"; return 0 ;;
        11:16) echo "Xi’an Morebeck Semiconductor Tech Co"; return 0 ;;
        11:17) echo "Kingbank Technology Co Ltd"; return 0 ;;
        11:18) echo "ITRenew Inc"; return 0 ;;
        11:19) echo "Shenzhen Eaget Innovation Tech Ltd"; return 0 ;;
        11:20) echo "Jazer"; return 0 ;;
        11:21) echo "Xiamen Semiconductor Investment Group"; return 0 ;;
        11:22) echo "Guangzhou Longdao Network Tech Co"; return 0 ;;
        11:23) echo "Shenzhen Futian SEC Electronic Market"; return 0 ;;
        11:24) echo "Allegro Microsystems LLC"; return 0 ;;
        11:25) echo "Hunan RunCore Innovation Technology"; return 0 ;;
        11:26) echo "C-Corsa Technology"; return 0 ;;
        11:27) echo "Zhuhai Chuangfeixin Technology Co Ltd"; return 0 ;;
        11:28) echo "Beijing InnoMem Technologies Co Ltd"; return 0 ;;
        11:29) echo "YooTin"; return 0 ;;
        11:30) echo "Shenzhen Pengxiong Technology Co Ltd"; return 0 ;;
        11:31) echo "Dongguan Yingbang Commercial Trading Co"; return 0 ;;
        11:32) echo "Shenzhen Ronisys Electronics Co Ltd"; return 0 ;;
        11:33) echo "Hongkong Xinlan Guangke Co Ltd"; return 0 ;;
        11:34) echo "Apex Microelectronics Co Ltd"; return 0 ;;
        11:35) echo "Beijing Hongda Jinming Technology Co Ltd"; return 0 ;;
        11:36) echo "Ling Rui Technology (Shenzhen) Co Ltd"; return 0 ;;
        11:37) echo "Hongkong Hyunion Electronics Co Ltd"; return 0 ;;
        11:38) echo "Starsystems Inc"; return 0 ;;
        11:39) echo "Shenzhen Yingjiaxun Industrial Co Ltd"; return 0 ;;
        11:40) echo "Dongguan Crown Code Electronic Commerce"; return 0 ;;
        11:41) echo "Monolithic Power Systems Inc"; return 0 ;;
        11:42) echo "WuHan SenNaiBo E-Commerce Co Ltd"; return 0 ;;
        11:43) echo "Hangzhou Hikstorage Technology Co"; return 0 ;;
        11:44) echo "Shenzhen Goodix Technology Co Ltd"; return 0 ;;
        11:45) echo "Aigo Electronic Technology Co Ltd"; return 0 ;;
        11:46) echo "Hefei Konsemi Storage Technology Co Ltd"; return 0 ;;
        11:47) echo "Cactus Technologies Limited"; return 0 ;;
        11:48) echo "DSIN"; return 0 ;;
        11:49) echo "Blu Wireless Technology"; return 0 ;;
        11:50) echo "Nanjing UCUN Technology Inc"; return 0 ;;
        11:51) echo "Acacia Communications"; return 0 ;;
        11:52) echo "Beijinjinshengyihe Technology Co Ltd"; return 0 ;;
        11:53) echo "Zyzyx"; return 0 ;;
        11:54) echo "T-HEAD Semiconductor Co Ltd"; return 0 ;;
        11:55) echo "Shenzhen Hystou Technology Co Ltd"; return 0 ;;
        11:56) echo "Syzexion"; return 0 ;;
        11:57) echo "Kembona"; return 0 ;;
        11:58) echo "Qingdao Thunderobot Technology Co Ltd"; return 0 ;;
        11:59) echo "Morse Micro"; return 0 ;;
        11:60) echo "Shenzhen Envida Technology Co Ltd"; return 0 ;;
        11:61) echo "UDStore Solution Limited"; return 0 ;;
        11:62) echo "Shunlie"; return 0 ;;
        11:63) echo "Shenzhen Xin Hong Rui Tech Ltd"; return 0 ;;
        11:64) echo "Shenzhen Yze Technology Co Ltd"; return 0 ;;
        11:65) echo "Shenzhen Huang Pu He Xin Technology"; return 0 ;;
        11:66) echo "Xiamen Pengpai Microelectronics Co Ltd"; return 0 ;;
        11:67) echo "JISHUN"; return 0 ;;
        11:68) echo "Shenzhen WODPOSIT Technology Co"; return 0 ;;
        11:69) echo "Unistar"; return 0 ;;
        11:70) echo "UNICORE Electronic (Suzhou) Co Ltd"; return 0 ;;
        11:71) echo "Axonne Inc"; return 0 ;;
        11:72) echo "Shenzhen SOVERECA Technology Co"; return 0 ;;
        11:73) echo "Dire Wolf"; return 0 ;;
        11:74) echo "Whampoa Core Technology Co Ltd"; return 0 ;;
        11:75) echo "CSI Halbleiter GmbH"; return 0 ;;
        11:76) echo "ONE Semiconductor"; return 0 ;;
        11:77) echo "SimpleMachines Inc"; return 0 ;;
        11:78) echo "Shenzhen Chengyi Qingdian Electronic"; return 0 ;;
        11:79) echo "Shenzhen Xinlianxin Network Technology"; return 0 ;;
        11:80) echo "Vayyar Imaging Ltd"; return 0 ;;
        11:81) echo "Paisen Network Technology Co Ltd"; return 0 ;;
        11:82) echo "Shenzhen Fengwensi Technology Co Ltd"; return 0 ;;
        11:83) echo "Caplink Technology Limited"; return 0 ;;
        11:84) echo "JJT Solution Co Ltd"; return 0 ;;
        11:85) echo "HOSIN Global Electronics Co Ltd"; return 0 ;;
        11:86) echo "Shenzhen KingDisk Century Technology"; return 0 ;;
        11:87) echo "SOYO"; return 0 ;;
        11:88) echo "DIT Technology Co Ltd"; return 0 ;;
        11:89) echo "iFound"; return 0 ;;
        11:90) echo "Aril Computer Company"; return 0 ;;
        11:91) echo "ASUS"; return 0 ;;
        11:92) echo "Shenzhen Ruiyingtong Technology Co"; return 0 ;;
        11:93) echo "HANA Micron"; return 0 ;;
        11:94) echo "RANSOR"; return 0 ;;
        11:95) echo "Axiado Corporation"; return 0 ;;
        11:96) echo "Tesla Corporation"; return 0 ;;
        11:97) echo "Pingtouge (Shanghai) Semiconductor Co"; return 0 ;;
        11:98) echo "S3Plus Technologies SA"; return 0 ;;
        11:99) echo "Integrated Silicon Solution Israel Ltd"; return 0 ;;
        11:100) echo "GreenWaves Technologies"; return 0 ;;
        11:101) echo "NUVIA Inc"; return 0 ;;
        11:102) echo "Guangzhou Shuvrwine Technology Co"; return 0 ;;
        11:103) echo "Shenzhen Hangshun Chip Technology"; return 0 ;;
        11:104) echo "Chengboliwei Electronic Business"; return 0 ;;
        11:105) echo "Kowin Memory Technology Co Ltd"; return 0 ;;
        11:106) echo "Euronet Technology Inc"; return 0 ;;
        11:107) echo "SCY"; return 0 ;;
        11:108) echo "Shenzhen Xinhongyusheng Electrical"; return 0 ;;
        11:109) echo "PICOCOM"; return 0 ;;
        11:110) echo "Shenzhen Toooogo Memory Technology"; return 0 ;;
        11:111) echo "VLSI Solution"; return 0 ;;
        11:112) echo "Costar Electronics Inc"; return 0 ;;
        11:113) echo "Shenzhen Huatop Technology Co Ltd"; return 0 ;;
        11:114) echo "Inspur Electronic Information Industry"; return 0 ;;
        11:115) echo "Shenzhen Boyuan Computer Technology"; return 0 ;;
        11:116) echo "Beijing Welldisk Electronics Co Ltd"; return 0 ;;
        11:117) echo "Suzhou EP Semicon Co Ltd"; return 0 ;;
        11:118) echo "Zhejiang Dahua Memory Technology"; return 0 ;;
        11:119) echo "Virtu Financial"; return 0 ;;
        11:120) echo "Datotek International Co Ltd"; return 0 ;;
        11:121) echo "Telecom and Microelectronics Industries"; return 0 ;;
        11:122) echo "Echo Technology Ltd"; return 0 ;;
        11:123) echo "APEX-INFO"; return 0 ;;
        11:124) echo "Yingpark"; return 0 ;;
        11:125) echo "Shenzhen Bigway Tech Co Ltd"; return 0 ;;
        12:0) echo "Beijing Haawking Technology Co Ltd"; return 0 ;;
        12:1) echo "Open HW Group"; return 0 ;;
        12:2) echo "JHICC"; return 0 ;;
        12:3) echo "ncoder AG"; return 0 ;;
        12:4) echo "ThinkTech Information Technology Co"; return 0 ;;
        12:5) echo "Shenzhen Chixingzhe Technology Co Ltd"; return 0 ;;
        12:6) echo "Skywalker"; return 0 ;;
        12:7) echo "Shenzhen Kaizhuoyue Electronics Co Ltd"; return 0 ;;
        12:8) echo "Shenzhen YC Storage Technology Co Ltd"; return 0 ;;
        12:9) echo "Shenzhen Chixingzhe Technology Co"; return 0 ;;
        12:10) echo "Wink Semiconductor (Shenzhen) Co Ltd"; return 0 ;;
        12:11) echo "AISTOR"; return 0 ;;
        12:12) echo "Palma Ceia SemiDesign"; return 0 ;;
        12:13) echo "EM Microelectronic-Marin SA"; return 0 ;;
        12:14) echo "Shenzhen Monarch Memory Technology"; return 0 ;;
    esac
    echo "$raw"
    return 1
}
