#!/usr/bin/env bash
# wellutils language library
# Source this file to load translations: source /usr/share/wellutils/lang.sh
# Set language via: ${XDG_CONFIG_HOME:-$HOME/.config}/wellutils/lang.conf
#                    or the WELLUTILS_LANG environment variable

_WELLUTILS_LANG_FILE="${XDG_CONFIG_HOME:-${HOME:-/tmp}/.config}/wellutils/lang.conf"

# Read saved language preference
if [[ -f "$_WELLUTILS_LANG_FILE" ]]; then
    _WELLUTILS_LANG=$( { sed -n '/^[A-Z]/{p;q}' "$_WELLUTILS_LANG_FILE" 2>/dev/null || true; } | tr -d '[:space:]')
fi

# Env var overrides file
WELLUTILS_LANG="${WELLUTILS_LANG:-${_WELLUTILS_LANG:-EN}}"

# Validate (uppercase via tr — bash 3.2-compatible, no ${^^})
WELLUTILS_LANG=$(printf '%s' "${WELLUTILS_LANG:-${_WELLUTILS_LANG:-EN}}" | tr '[:lower:]' '[:upper:]')
case "$WELLUTILS_LANG" in
    RU) WELLUTILS_LANG="RU" ;;
    *)  WELLUTILS_LANG="EN" ;;
esac

_t_EN() {
    case "$1" in
        loaded)             printf '%s' "loaded" ;;
        not_found)          printf '%s' "not found" ;;
        no_data)            printf '%s' "No data available" ;;
        usb_title)          printf '%s' "USB Device Explorer" ;;
        usb_devices)        printf '%s' "Devices" ;;
        usb_ids_db)         printf '%s' "IDS Database" ;;
        usb_bus)            printf '%s' "Bus" ;;
        usb_manufacturer)   printf '%s' "Manufacturer" ;;
        usb_speed)          printf '%s' "Speed" ;;
        usb_driver)         printf '%s' "Driver" ;;
        usb_serial)         printf '%s' "Serial" ;;
        usb_type)           printf '%s' "Type" ;;
        usb_unknown)        printf '%s' "Unknown Device" ;;
        usb_legend)         printf '%s' "Legend" ;;
        usb_speed_15)       printf '%s' "USB 1.0 (1.5 Mbps)" ;;
        usb_speed_12)       printf '%s' "USB 1.1 (12 Mbps)" ;;
        usb_speed_480)      printf '%s' "USB 2.0 (480 Mbps)" ;;
        usb_speed_5000)     printf '%s' "USB 3.0 (5 Gbps)" ;;
        usb_speed_10000)    printf '%s' "USB 3.1 (10 Gbps)" ;;
        usb_speed_20000)    printf '%s' "USB 3.2 (20 Gbps)" ;;
        usb_speed_unknown)  printf 'Unknown (%s Mbps)' "$2" ;;
        usb_type_hub)       printf '%s' "Hub" ;;
        usb_type_webcam)    printf '%s' "Webcam" ;;
        usb_type_video)     printf '%s' "Video" ;;
        usb_type_keyboard)  printf '%s' "Keyboard" ;;
        usb_type_mouse)     printf '%s' "Mouse" ;;
        usb_type_tablet)    printf '%s' "Graphics Tablet" ;;
        usb_type_audio)     printf '%s' "Audio" ;;
        usb_type_hid)       printf '%s' "HID Device" ;;
        usb_type_storage)   printf '%s' "Storage" ;;
        usb_type_printer)   printf '%s' "Printer" ;;
        usb_type_data)      printf '%s' "CDC/Data" ;;
        usb_type_phone)     printf '%s' "Phone" ;;
        usb_type_misc)      printf '%s' "Misc" ;;
        usb_type_network)   printf '%s' "Network" ;;
        usb_type_vendor)    printf '%s' "Vendor-Specific" ;;
        usb_type_device)    printf '%s' "Device" ;;
        usb_type_gamepad)   printf '%s' "Gamepad" ;;
        per_title)          printf '%s' "Peripherals Report" ;;
        per_input)          printf '%s' "Input Devices" ;;
        per_media)          printf '%s' "Media" ;;
        per_other)          printf '%s' "Other Devices" ;;
        per_usb)            printf '%s' "USB Devices" ;;
        per_displays)       printf '%s' "Displays" ;;
        per_audio)          printf '%s' "Audio" ;;
        per_usb_none)       printf '%s' "No USB devices found" ;;
        per_displays_none)  printf '%s' "No displays detected" ;;
        per_audio_none)     printf '%s' "No audio devices detected" ;;
        per_unknown)        printf '%s' "Unknown" ;;
        per_vendor)         printf '%s' "Vendor" ;;
        per_interface)      printf '%s' "Interface" ;;
        per_if_dp)          printf '%s' "DisplayPort" ;;
        per_if_hdmi)        printf '%s' "HDMI" ;;
        per_if_dvi)         printf '%s' "DVI" ;;
        per_if_vga)         printf '%s' "VGA" ;;
        per_if_edp)         printf '%s' "Embedded DisplayPort" ;;
        pci_title)          printf '%s' "PCI Device Explorer" ;;
        pci_total)          printf '%s' "Total devices" ;;
        pci_drv)            printf '%s' "Drv" ;;
        pci_class_legacy)       printf '%s' "Legacy Device" ;;
        pci_class_storage)      printf '%s' "Mass Storage Controller" ;;
        pci_class_network)      printf '%s' "Network Controller" ;;
        pci_class_display)      printf '%s' "Display Controller" ;;
        pci_class_multimedia)   printf '%s' "Multimedia Controller" ;;
        pci_class_memory)       printf '%s' "Memory Controller" ;;
        pci_class_bridge)       printf '%s' "Bridge Device" ;;
        pci_class_comm)         printf '%s' "Communication Controller" ;;
        pci_class_system)       printf '%s' "System Peripheral" ;;
        pci_class_input)        printf '%s' "Input Device" ;;
        pci_class_dock)         printf '%s' "Docking Station" ;;
        pci_class_processor)    printf '%s' "Processor" ;;
        pci_class_serial)       printf '%s' "Serial Bus Controller" ;;
        pci_class_wireless)     printf '%s' "Wireless Controller" ;;
        pci_class_vendor)       printf '%s' "Vendor-Specific" ;;
        pci_class_unknown)      printf '%s' "Unknown" ;;
        blk_title)          printf '%s' "Block Device Explorer" ;;
        blk_summary)        printf '%s' "DISK SUMMARY" ;;
        blk_virtual)        printf '%s' "VIRTUAL / LOOP DEVICES" ;;
        blk_serial)         printf '%s' "Serial" ;;
        blk_removable)      printf '%s' "Removable" ;;
        blk_ssd)            printf '%s' "SSD" ;;
        blk_hdd)            printf '%s' "HDD" ;;
        blk_total)          printf '%s' "Total" ;;
        blk_disks)          printf '%s' "disks" ;;
        blk_partitions)     printf '%s' "partitions" ;;
        blk_firmware)       printf '%s' "Firmware" ;;
        blk_transport)      printf '%s' "Transport" ;;
        blk_model)          printf '%s' "Model" ;;
        blk_size)           printf '%s' "Size" ;;
        blk_type)           printf '%s' "Type" ;;
        blk_detail)         printf '%s' "DISK DETAIL" ;;
        blk_parts)          printf '%s' "PARTITIONS" ;;
        blk_smart)          printf '%s' "S.M.A.R.T. STATUS" ;;
        blk_smart_health)   printf '%s' "Health" ;;
        blk_smart_pass)     printf '%s' "PASSED" ;;
        blk_smart_fail)     printf '%s' "FAILED" ;;
        blk_smart_unknown)  printf '%s' "unknown" ;;
        blk_smart_no)       printf '%s' "S.M.A.R.T. not supported" ;;
        blk_smart_na)       printf '%s' "S.M.A.R.T. data unavailable (run as root)" ;;
        blk_smart_attr)     printf '%s' "ATTRIBUTE" ;;
        blk_smart_value)    printf '%s' "VAL" ;;
        blk_smart_worst)    printf '%s' "WORST" ;;
        blk_smart_thresh)   printf '%s' "THRESH" ;;
        blk_smart_raw)      printf '%s' "RAW" ;;
        blk_smart_risk)     printf '%s' "risk" ;;
        blk_health_good)    printf '%s' "HEALTHY" ;;
        blk_health_warn)    printf '%s' "ATTENTION" ;;
        blk_health_bad)     printf '%s' "CRITICAL" ;;
        cpu_title)          printf '%s' "CPU Overview" ;;
        cpu_summary)        printf '%s' "PROCESSOR" ;;
        cpu_load)           printf '%s' "PER-CORE LOAD / FREQ" ;;
        cpu_model)          printf '%s' "Model" ;;
        cpu_arch)           printf '%s' "Architecture" ;;
        cpu_sockets)        printf '%s' "Sockets" ;;
        cpu_cores)          printf '%s' "Cores" ;;
        cpu_threads)        printf '%s' "Threads" ;;
        cpu_freq)           printf '%s' "Frequency" ;;
        cpu_base)           printf '%s' "base" ;;
        cpu_turbo)          printf '%s' "max" ;;
        cpu_governor)       printf '%s' "Governor" ;;
        cpu_caches)         printf '%s' "Caches" ;;
        cpu_virt)           printf '%s' "Virtualization" ;;
        cpu_features)       printf '%s' "Features" ;;
        cpu_core)           printf '%s' "core" ;;
        cpu_cur)            printf '%s' "current" ;;
        cpu_online)         printf '%s' "On-line" ;;
        cpu_hv)             printf '%s' "Hypervisor" ;;
        cpu_turbo_boost)    printf '%s' "Turbo Boost" ;;
        gpu_title)          printf '%s' "GPU Overview" ;;
        gpu_summary)        printf '%s' "GRAPHICS ADAPTERS" ;;
        gpu_detail)         printf '%s' "DETAILS" ;;
        gpu_vendor)         printf '%s' "Vendor" ;;
        gpu_driver)         printf '%s' "Driver" ;;
        gpu_vram)           printf '%s' "VRAM" ;;
        gpu_temp)           printf '%s' "Temperature" ;;
        gpu_util)           printf '%s' "Utilization" ;;
        gpu_clocks)         printf '%s' "Clocks" ;;
        gpu_power)          printf '%s' "Power" ;;
        gpu_fan)            printf '%s' "Fan" ;;
        gpu_bus)            printf '%s' "Bus" ;;
        gpu_memory)         printf '%s' "Memory" ;;
        gpu_nvidia_none)    printf '%s' "nvidia-smi not found" ;;
        gpu_none)           printf '%s' "No GPU detected" ;;
        mem_title)          printf '%s' "Memory Overview" ;;
        mem_ram)            printf '%s' "PHYSICAL MEMORY (RAM)" ;;
        mem_swap)           printf '%s' "SWAP" ;;
        mem_zram)           printf '%s' "ZRAM Compressed RAM" ;;
        mem_huge)           printf '%s' "Huge Pages" ;;
        mem_numa)           printf '%s' "NUMA Nodes" ;;
        mem_total)          printf '%s' "Total" ;;
        mem_used)           printf '%s' "Used" ;;
        mem_available)      printf '%s' "Available" ;;
        mem_buffers)        printf '%s' "Buffers" ;;
        mem_cached)         printf '%s' "Cached" ;;
        mem_shared)         printf '%s' "Shared" ;;
        mem_free)           printf '%s' "Free" ;;
        mem_size)           printf '%s' "Size" ;;
        mem_algorithm)      printf '%s' "Algorithm" ;;
        mem_pct_used)       printf '%s' "used" ;;
        mem_no_swap)        printf '%s' "No swap configured" ;;
        mod_title)          printf '%s' "Kernel Module Explorer" ;;
        mod_total)          printf '%s' "Total modules" ;;
        mod_total_size)     printf '%s' "Total size" ;;
        mod_top10)          printf '%s' "TOP 10 BY SIZE" ;;
        mod_gpu_dri)        printf '%s' "GPU/DRI" ;;
        mod_audio)          printf '%s' "Audio" ;;
        mod_usb)            printf '%s' "USB" ;;
        mod_storage)        printf '%s' "Storage" ;;
        mod_filesystem)     printf '%s' "Filesystem" ;;
        mod_networking)     printf '%s' "Networking" ;;
        mod_wifi)           printf '%s' "WiFi" ;;
        mod_bluetooth)      printf '%s' "Bluetooth" ;;
        mod_virtualization) printf '%s' "Virtualization" ;;
        mod_display)        printf '%s' "Display" ;;
        mod_bus)            printf '%s' "Bus" ;;
        mod_timer)          printf '%s' "Timer" ;;
        mod_cpu_virt)       printf '%s' "CPU/Virt" ;;
        mod_netfs)          printf '%s' "Network FS" ;;
        mod_size_legend)    printf '%s' "Size" ;;
        mod_size_small)     printf '%s' "<64KB" ;;
        mod_size_med)       printf '%s' "<256KB" ;;
        mod_size_large)     printf '%s' "<1MB" ;;
        mod_size_huge)      printf '%s' ">1MB" ;;
        sens_title)         printf '%s' "System Temperature Monitor" ;;
        sens_sys_overview)  printf '%s' "SYSTEM OVERVIEW" ;;
        sens_cpu_cores)     printf '%s' "CPU CORES" ;;
        sens_gpu)           printf '%s' "GPU" ;;
        sens_acpi)          printf '%s' "ACPI / MOTHERBOARD" ;;
        sens_thermal)       printf '%s' "THERMAL ZONES" ;;
        sens_sensors)       printf '%s' "SENSOR CHIPS" ;;
        sens_storage)       printf '%s' "STORAGE" ;;
        sens_cooling)       printf '%s' "COOLING" ;;
        sens_no_cpu)        printf '%s' "No CPU sensors found" ;;
        sens_no_gpu)        printf '%s' "No NVIDIA GPU detected" ;;
        sens_no_acpi)       printf '%s' "No ACPI temperature zones" ;;
        sens_all_covered)   printf '%s' "(all zones covered by hwmon)" ;;
        sens_no_chips)      printf '%s' "(no additional sensor chips)" ;;
        sens_no_disk)       printf '%s' "No disk temperature data available" ;;
        sens_cpu)           printf '%s' "CPU" ;;
        sens_load)          printf '%s' "Load" ;;
        sens_ram)           printf '%s' "RAM" ;;
        sens_uptime)        printf '%s' "Uptime" ;;
        sens_fan)           printf '%s' "Fan" ;;
        sens_no_fan_rpm)    printf '%s' "No fan RPM data available" ;;
        sens_cstates)       printf '%s' "CPU C-states" ;;
        sens_powerclamp)    printf '%s' "Powerclamp" ;;
        sens_devices)       printf '%s' "device(s)" ;;
        sens_throttle)      printf '%s' "throttle" ;;
        sens_active)        printf '%s' "active" ;;
        sens_min)           printf '%s' "MIN" ;;
        sens_avg)           printf '%s' "AVG" ;;
        sens_max)           printf '%s' "MAX" ;;
        sens_acpi_fans)     printf '%s' "ACPI fan control interface(s)" ;;
        hw_title)           printf '%s' "Hardware Report" ;;
        hw_cpu)             printf '%s' "CPU" ;;
        hw_gpu)             printf '%s' "GPU" ;;
        hw_board)           printf '%s' "Motherboard" ;;
        hw_bios)            printf '%s' "BIOS" ;;
        hw_ram)             printf '%s' "RAM" ;;
        hw_storage)         printf '%s' "Storage" ;;
        hw_cooling)         printf '%s' "Fan" ;;
        hw_cores)           printf '%s' "cores" ;;
        hw_threads)         printf '%s' "threads" ;;
        hw_pn)              printf '%s' "PN" ;;
        hw_unknown)         printf '%s' "unknown" ;;
        hw_ram_none)        printf '%s' "no memory metadata available" ;;
        hw_network)         printf '%s' "Network" ;;
        hw_battery)         printf '%s' "Battery" ;;
    esac
}

_t_RU() {
    case "$1" in
        loaded)             printf '%s' "загружена" ;;
        not_found)          printf '%s' "не найдена" ;;
        no_data)            printf '%s' "Нет данных" ;;
        usb_title)          printf '%s' "Обзор USB-устройств" ;;
        usb_devices)        printf '%s' "Устройства" ;;
        usb_ids_db)         printf '%s' "БД IDS" ;;
        usb_bus)            printf '%s' "Шина" ;;
        usb_manufacturer)   printf '%s' "Производитель" ;;
        usb_speed)          printf '%s' "Скорость" ;;
        usb_driver)         printf '%s' "Драйвер" ;;
        usb_serial)         printf '%s' "Серийный №" ;;
        usb_type)           printf '%s' "Тип" ;;
        usb_unknown)        printf '%s' "Неизвестное устройство" ;;
        usb_legend)         printf '%s' "Легенда" ;;
        usb_speed_15)       printf '%s' "USB 1.0 (1.5 Мбит/с)" ;;
        usb_speed_12)       printf '%s' "USB 1.1 (12 Мбит/с)" ;;
        usb_speed_480)      printf '%s' "USB 2.0 (480 Мбит/с)" ;;
        usb_speed_5000)     printf '%s' "USB 3.0 (5 Гбит/с)" ;;
        usb_speed_10000)    printf '%s' "USB 3.1 (10 Гбит/с)" ;;
        usb_speed_20000)    printf '%s' "USB 3.2 (20 Гбит/с)" ;;
        usb_speed_unknown)  printf 'Неизвестно (%s Мбит/с)' "$2" ;;
        usb_type_hub)       printf '%s' "Хаб" ;;
        usb_type_webcam)    printf '%s' "Веб-камера" ;;
        usb_type_video)     printf '%s' "Видео" ;;
        usb_type_keyboard)  printf '%s' "Клавиатура" ;;
        usb_type_mouse)     printf '%s' "Мышь" ;;
        usb_type_tablet)    printf '%s' "Графический планшет" ;;
        usb_type_audio)     printf '%s' "Аудио" ;;
        usb_type_hid)       printf '%s' "HID-устройство" ;;
        usb_type_storage)   printf '%s' "Накопитель" ;;
        usb_type_printer)   printf '%s' "Принтер" ;;
        usb_type_data)      printf '%s' "CDC/Данные" ;;
        usb_type_phone)     printf '%s' "Телефон" ;;
        usb_type_misc)      printf '%s' "Прочее" ;;
        usb_type_network)   printf '%s' "Сеть" ;;
        usb_type_vendor)    printf '%s' "Вендор-специфичное" ;;
        usb_type_device)    printf '%s' "Устройство" ;;
        usb_type_gamepad)   printf '%s' "Геймпад" ;;
        per_title)          printf '%s' "Отчёт о периферии" ;;
        per_input)          printf '%s' "Устройства ввода" ;;
        per_media)          printf '%s' "Мультимедиа" ;;
        per_other)          printf '%s' "Прочие устройства" ;;
        per_usb)            printf '%s' "USB-устройства" ;;
        per_displays)       printf '%s' "Мониторы" ;;
        per_audio)          printf '%s' "Звук" ;;
        per_usb_none)       printf '%s' "USB-устройства не найдены" ;;
        per_displays_none)  printf '%s' "Мониторы не обнаружены" ;;
        per_audio_none)     printf '%s' "Звуковые устройства не обнаружены" ;;
        per_unknown)        printf '%s' "Неизвестно" ;;
        per_vendor)         printf '%s' "Производитель" ;;
        per_interface)      printf '%s' "Интерфейс" ;;
        per_if_dp)          printf '%s' "DisplayPort" ;;
        per_if_hdmi)        printf '%s' "HDMI" ;;
        per_if_dvi)         printf '%s' "DVI" ;;
        per_if_vga)         printf '%s' "VGA" ;;
        per_if_edp)         printf '%s' "Embedded DisplayPort" ;;
        pci_title)          printf '%s' "Обзор PCI-устройств" ;;
        pci_total)          printf '%s' "Всего устройств" ;;
        pci_drv)            printf '%s' "Дрв" ;;
        pci_class_legacy)       printf '%s' "Устаревшее устройство" ;;
        pci_class_storage)      printf '%s' "Контроллер накопителей" ;;
        pci_class_network)      printf '%s' "Сетевой контроллер" ;;
        pci_class_display)      printf '%s' "Видеоконтроллер" ;;
        pci_class_multimedia)   printf '%s' "Мультимедиа" ;;
        pci_class_memory)       printf '%s' "Контроллер памяти" ;;
        pci_class_bridge)       printf '%s' "Мост" ;;
        pci_class_comm)         printf '%s' "Контроллер связи" ;;
        pci_class_system)       printf '%s' "Системное устройство" ;;
        pci_class_input)        printf '%s' "Устройство ввода" ;;
        pci_class_dock)         printf '%s' "Станция" ;;
        pci_class_processor)    printf '%s' "Процессор" ;;
        pci_class_serial)       printf '%s' "Последовательная шина" ;;
        pci_class_wireless)     printf '%s' "Беспроводной контроллер" ;;
        pci_class_vendor)       printf '%s' "Вендор-специфичное" ;;
        pci_class_unknown)      printf '%s' "Неизвестно" ;;
        blk_title)          printf '%s' "Обзор блочных устройств" ;;
        blk_summary)        printf '%s' "СВОДКА ПО ДИСКАМ" ;;
        blk_virtual)        printf '%s' "ВИРТУАЛЬНЫЕ / LOOP" ;;
        blk_serial)         printf '%s' "Серийный №" ;;
        blk_removable)      printf '%s' "Съёмный" ;;
        blk_ssd)            printf '%s' "SSD" ;;
        blk_hdd)            printf '%s' "HDD" ;;
        blk_total)          printf '%s' "Итого" ;;
        blk_disks)          printf '%s' "дисков" ;;
        blk_partitions)     printf '%s' "разделов" ;;
        blk_firmware)       printf '%s' "Прошивка" ;;
        blk_transport)      printf '%s' "Интерфейс" ;;
        blk_model)          printf '%s' "Модель" ;;
        blk_size)           printf '%s' "Размер" ;;
        blk_type)           printf '%s' "Тип" ;;
        blk_detail)         printf '%s' "ДЕТАЛИ ДИСКА" ;;
        blk_parts)          printf '%s' "РАЗДЕЛЫ" ;;
        blk_smart)          printf '%s' "СТАТУС S.M.A.R.T." ;;
        blk_smart_health)   printf '%s' "Состояние" ;;
        blk_smart_pass)     printf '%s' "ПРОЙДЕНО" ;;
        blk_smart_fail)     printf '%s' "ОТКАЗ" ;;
        blk_smart_unknown)  printf '%s' "неизвестно" ;;
        blk_smart_no)       printf '%s' "S.M.A.R.T. не поддерживается" ;;
        blk_smart_na)       printf '%s' "Данные S.M.A.R.T. недоступны (запустите от root)" ;;
        blk_smart_attr)     printf '%s' "АТРИБУТ" ;;
        blk_smart_value)    printf '%s' "VAL" ;;
        blk_smart_worst)    printf '%s' "ХУДШ" ;;
        blk_smart_thresh)   printf '%s' "ПОРОГ" ;;
        blk_smart_raw)      printf '%s' "RAW" ;;
        blk_smart_risk)     printf '%s' "риск" ;;
        blk_health_good)    printf '%s' "ЗДОРОВ" ;;
        blk_health_warn)    printf '%s' "ВНИМАНИЕ" ;;
        blk_health_bad)     printf '%s' "КРИТИЧНО" ;;
        cpu_title)          printf '%s' "Обзор CPU" ;;
        cpu_summary)        printf '%s' "ПРОЦЕССОР" ;;
        cpu_load)           printf '%s' "НАГРУЗКА ЯДЕР / ЧАСТОТА" ;;
        cpu_model)          printf '%s' "Модель" ;;
        cpu_arch)           printf '%s' "Архитектура" ;;
        cpu_sockets)        printf '%s' "Сокеты" ;;
        cpu_cores)          printf '%s' "Ядра" ;;
        cpu_threads)        printf '%s' "Потоки" ;;
        cpu_freq)           printf '%s' "Частота" ;;
        cpu_base)           printf '%s' "база" ;;
        cpu_turbo)          printf '%s' "макс" ;;
        cpu_governor)       printf '%s' "Губернатор" ;;
        cpu_caches)         printf '%s' "Кэши" ;;
        cpu_virt)           printf '%s' "Виртуализация" ;;
        cpu_features)       printf '%s' "Фичи" ;;
        cpu_core)           printf '%s' "ядро" ;;
        cpu_cur)            printf '%s' "текущая" ;;
        cpu_online)         printf '%s' "В сети" ;;
        cpu_hv)             printf '%s' "Гипервизор" ;;
        cpu_turbo_boost)    printf '%s' "Turbo Boost" ;;
        gpu_title)          printf '%s' "Обзор GPU" ;;
        gpu_summary)        printf '%s' "ВИДЕОАДАПТЕРЫ" ;;
        gpu_detail)         printf '%s' "ДЕТАЛИ" ;;
        gpu_vendor)         printf '%s' "Производитель" ;;
        gpu_driver)         printf '%s' "Драйвер" ;;
        gpu_vram)           printf '%s' "VRAM" ;;
        gpu_temp)           printf '%s' "Температура" ;;
        gpu_util)           printf '%s' "Загрузка" ;;
        gpu_clocks)         printf '%s' "Частоты" ;;
        gpu_power)          printf '%s' "Питание" ;;
        gpu_fan)            printf '%s' "Вентилятор" ;;
        gpu_bus)            printf '%s' "Шина" ;;
        gpu_memory)         printf '%s' "Память" ;;
        gpu_nvidia_none)    printf '%s' "nvidia-smi не найден" ;;
        gpu_none)           printf '%s' "GPU не обнаружен" ;;
        mem_title)          printf '%s' "Обзор памяти" ;;
        mem_ram)            printf '%s' "ФИЗИЧЕСКАЯ ПАМЯТЬ (RAM)" ;;
        mem_swap)           printf '%s' "ПОДКАЧКА" ;;
        mem_zram)           printf '%s' "ZRAM — сжатая RAM" ;;
        mem_huge)           printf '%s' "Большие страницы" ;;
        mem_numa)           printf '%s' "NUMA-ноды" ;;
        mem_total)          printf '%s' "Всего" ;;
        mem_used)           printf '%s' "Использовано" ;;
        mem_available)      printf '%s' "Доступно" ;;
        mem_buffers)        printf '%s' "Буферы" ;;
        mem_cached)         printf '%s' "Кэш" ;;
        mem_shared)         printf '%s' "Разделяемая" ;;
        mem_free)           printf '%s' "Свободно" ;;
        mem_size)           printf '%s' "Размер" ;;
        mem_algorithm)      printf '%s' "Алгоритм" ;;
        mem_pct_used)       printf '%s' "использовано" ;;
        mem_no_swap)        printf '%s' "Подкачка не настроена" ;;
        mod_title)          printf '%s' "Обзор модулей ядра" ;;
        mod_total)          printf '%s' "Всего модулей" ;;
        mod_total_size)     printf '%s' "Общий размер" ;;
        mod_top10)          printf '%s' "ТОП-10 ПО РАЗМЕРУ" ;;
        mod_gpu_dri)        printf '%s' "GPU/DRI" ;;
        mod_audio)          printf '%s' "Аудио" ;;
        mod_usb)            printf '%s' "USB" ;;
        mod_storage)        printf '%s' "Накопители" ;;
        mod_filesystem)     printf '%s' "Файловая система" ;;
        mod_networking)     printf '%s' "Сеть" ;;
        mod_wifi)           printf '%s' "WiFi" ;;
        mod_bluetooth)      printf '%s' "Bluetooth" ;;
        mod_virtualization) printf '%s' "Виртуализация" ;;
        mod_display)        printf '%s' "Дисплей" ;;
        mod_bus)            printf '%s' "Шина" ;;
        mod_timer)          printf '%s' "Таймер" ;;
        mod_cpu_virt)       printf '%s' "CPU/Вирт." ;;
        mod_netfs)          printf '%s' "Сетевые ФС" ;;
        mod_size_legend)    printf '%s' "Размер" ;;
        mod_size_small)     printf '%s' "<64КБ" ;;
        mod_size_med)       printf '%s' "<256КБ" ;;
        mod_size_large)     printf '%s' "<1МБ" ;;
        mod_size_huge)      printf '%s' ">1МБ" ;;
        sens_title)         printf '%s' "Мониторинг температуры" ;;
        sens_sys_overview)  printf '%s' "ОБЗОР СИСТЕМЫ" ;;
        sens_cpu_cores)     printf '%s' "ЯДРА CPU" ;;
        sens_gpu)           printf '%s' "GPU" ;;
        sens_acpi)          printf '%s' "ACPI / МАТЕРИНСКАЯ ПЛАТА" ;;
        sens_thermal)       printf '%s' "ТЕПЛОВЫЕ ЗОНЫ" ;;
        sens_sensors)       printf '%s' "ЧИПСЕНСОРЫ" ;;
        sens_storage)       printf '%s' "ХРАНИЛИЩЕ" ;;
        sens_cooling)       printf '%s' "ОХЛАЖДЕНИЕ" ;;
        sens_no_cpu)        printf '%s' "Датчики CPU не найдены" ;;
        sens_no_gpu)        printf '%s' "NVIDIA GPU не обнаружен" ;;
        sens_no_acpi)       printf '%s' "Нет ACPI-температурных зон" ;;
        sens_all_covered)   printf '%s' "(все зоны покрыты hwmon)" ;;
        sens_no_chips)      printf '%s' "(нет дополнительных датчиков)" ;;
        sens_no_disk)       printf '%s' "Данные о температуре дисков недоступны" ;;
        sens_cpu)           printf '%s' "CPU" ;;
        sens_load)          printf '%s' "Загрузка" ;;
        sens_ram)           printf '%s' "RAM" ;;
        sens_uptime)        printf '%s' "Аптайм" ;;
        sens_fan)           printf '%s' "Вентилятор" ;;
        sens_no_fan_rpm)    printf '%s' "Данные об оборотах вентиляторов недоступны" ;;
        sens_cstates)       printf '%s' "Состояния CPU" ;;
        sens_powerclamp)    printf '%s' "Powerclamp" ;;
        sens_devices)       printf '%s' "устройств" ;;
        sens_throttle)      printf '%s' "троттлинг" ;;
        sens_active)        printf '%s' "активно" ;;
        sens_min)           printf '%s' "МИН" ;;
        sens_avg)           printf '%s' "СРД" ;;
        sens_max)           printf '%s' "МАКС" ;;
        sens_acpi_fans)     printf '%s' "ACPI-интерфейсы управления вентиляторами" ;;
        hw_title)           printf '%s' "Отчёт о железе" ;;
        hw_cpu)             printf '%s' "CPU" ;;
        hw_gpu)             printf '%s' "GPU" ;;
        hw_board)           printf '%s' "Материнская плата" ;;
        hw_bios)            printf '%s' "BIOS" ;;
        hw_ram)             printf '%s' "ОЗУ" ;;
        hw_storage)         printf '%s' "Накопители" ;;
        hw_cooling)         printf '%s' "Вентилятор" ;;
        hw_cores)           printf '%s' "ядер" ;;
        hw_threads)         printf '%s' "потоков" ;;
        hw_pn)              printf '%s' "PN" ;;
        hw_unknown)         printf '%s' "неизвестно" ;;
        hw_ram_none)        printf '%s' "данные о памяти недоступны" ;;
        hw_network)         printf '%s' "Сеть" ;;
        hw_battery)         printf '%s' "Батарея" ;;
    esac
}

t() {
    case "$WELLUTILS_LANG" in
        RU) _t_RU "$@" ;;
        *)  _t_EN "$@" ;;
    esac
}
