# fish completion for wellgpu
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellgpu --help` -- do not edit.

complete -c wellgpu -f
complete -c wellgpu -l help -s h -d 'show this help'
complete -c wellgpu -l version -s V -d 'show version'
complete -c wellgpu -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellgpu -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellgpu -l plain -d 'plain text, no box drawing'
complete -c wellgpu -l box -d 'force box drawing even when piped'
complete -c wellgpu -l no-emoji -d 'drop emoji icons'
complete -c wellgpu -l emoji -d 'force emoji icons'
complete -c wellgpu -l json -d 'machine-readable JSON'
complete -c wellgpu -l short -d 'one-line compact status (status bars)'
complete -c wellgpu -l html -d 'standalone HTML report page'
complete -c wellgpu -l debug -d 'shell tracing'
