# fish completion for wellpower
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellpower --help` -- do not edit.

complete -c wellpower -f
complete -c wellpower -l help -s h -d 'show this help'
complete -c wellpower -l version -s V -d 'show version'
complete -c wellpower -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellpower -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellpower -l plain -d 'plain text, no box drawing'
complete -c wellpower -l box -d 'force box drawing even when piped'
complete -c wellpower -l no-emoji -d 'drop emoji icons'
complete -c wellpower -l emoji -d 'force emoji icons'
complete -c wellpower -l json -d 'machine-readable JSON'
complete -c wellpower -l short -d 'one-line compact status (status bars)'
complete -c wellpower -l html -d 'standalone HTML report page'
complete -c wellpower -l debug -d 'shell tracing'
