# fish completion for wellblock
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellblock --help` -- do not edit.

complete -c wellblock -f
complete -c wellblock -l help -s h -d 'show this help'
complete -c wellblock -l version -s V -d 'show version'
complete -c wellblock -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellblock -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellblock -l plain -d 'plain text, no box drawing'
complete -c wellblock -l box -d 'force box drawing even when piped'
complete -c wellblock -l no-emoji -d 'drop emoji icons'
complete -c wellblock -l emoji -d 'force emoji icons'
complete -c wellblock -l json -d 'machine-readable JSON'
complete -c wellblock -l html -d 'standalone HTML report page'
complete -c wellblock -l debug -d 'shell tracing'
complete -c wellblock -n 'not string match -q -- "-*" (commandline -ct)' -a '(path basename /sys/block/* 2>/dev/null | string match -v -r "^(loop|ram|zram)")' -d 'disk'
