# fish completion for wellmem
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellmem --help` -- do not edit.

complete -c wellmem -f
complete -c wellmem -l help -s h -d 'show this help'
complete -c wellmem -l version -s V -d 'show version'
complete -c wellmem -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellmem -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellmem -l plain -d 'plain text, no box drawing'
complete -c wellmem -l box -d 'force box drawing even when piped'
complete -c wellmem -l no-emoji -d 'drop emoji icons'
complete -c wellmem -l emoji -d 'force emoji icons'
complete -c wellmem -l json -d 'machine-readable JSON'
complete -c wellmem -l short -d 'one-line compact status (status bars)'
complete -c wellmem -l html -d 'standalone HTML report page'
complete -c wellmem -l debug -d 'shell tracing'
