# fish completion for wellper
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellper --help` -- do not edit.

complete -c wellper -f
complete -c wellper -l help -s h -d 'show this help'
complete -c wellper -l version -s V -d 'show version'
complete -c wellper -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellper -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellper -l plain -d 'plain text, no box drawing'
complete -c wellper -l box -d 'force box drawing even when piped'
complete -c wellper -l no-emoji -d 'drop emoji icons'
complete -c wellper -l emoji -d 'force emoji icons'
complete -c wellper -l json -d 'machine-readable JSON'
complete -c wellper -l html -d 'standalone HTML report page'
complete -c wellper -l debug -d 'shell tracing'
complete -c wellper -l groups -x -d 'USB groups: input,media,other or all'
complete -c wellper -l sections -x -d 'sections: usb,displays,audio,isa,pcmcia,pci or all'
complete -c wellper -l strict -d 'exit 1 when no devices are found'
complete -c wellper -l terse -d 'one-line summary'
