# fish completion for wellpci
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellpci --help` -- do not edit.

complete -c wellpci -f
complete -c wellpci -l help -s h -d 'show this help'
complete -c wellpci -l version -s V -d 'show version'
complete -c wellpci -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellpci -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellpci -l plain -d 'plain text, no box drawing'
complete -c wellpci -l box -d 'force box drawing even when piped'
complete -c wellpci -l no-emoji -d 'drop emoji icons'
complete -c wellpci -l emoji -d 'force emoji icons'
complete -c wellpci -l json -d 'machine-readable JSON'
complete -c wellpci -l html -d 'standalone HTML report page'
complete -c wellpci -l debug -d 'shell tracing'
complete -c wellpci -l all -d 'show all devices (default: expansion cards only)'
