# fish completion for wellusb
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellusb --help` -- do not edit.

complete -c wellusb -f
complete -c wellusb -l help -s h -d 'show this help'
complete -c wellusb -l version -s V -d 'show version'
complete -c wellusb -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellusb -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellusb -l plain -d 'plain text, no box drawing'
complete -c wellusb -l box -d 'force box drawing even when piped'
complete -c wellusb -l no-emoji -d 'drop emoji icons'
complete -c wellusb -l emoji -d 'force emoji icons'
complete -c wellusb -l json -d 'machine-readable JSON'
complete -c wellusb -l html -d 'standalone HTML report page'
complete -c wellusb -l debug -d 'shell tracing'
