# fish completion for wellmod
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellmod --help` -- do not edit.

complete -c wellmod -f
complete -c wellmod -l help -s h -d 'show this help'
complete -c wellmod -l version -s V -d 'show version'
complete -c wellmod -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellmod -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellmod -l plain -d 'plain text, no box drawing'
complete -c wellmod -l box -d 'force box drawing even when piped'
complete -c wellmod -l no-emoji -d 'drop emoji icons'
complete -c wellmod -l emoji -d 'force emoji icons'
complete -c wellmod -l json -d 'machine-readable JSON'
complete -c wellmod -l html -d 'standalone HTML report page'
complete -c wellmod -l debug -d 'shell tracing'
complete -c wellmod -l deps -x -a '(string replace -r " .*" "" < /proc/modules)' -d 'show module dependencies'
complete -c wellmod -l filter -s f -x -d 'filter modules by name'
