# fish completion for wellsensors
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellsensors --help` -- do not edit.

complete -c wellsensors -f
complete -c wellsensors -l help -s h -d 'show this help'
complete -c wellsensors -l version -s V -d 'show version'
complete -c wellsensors -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellsensors -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellsensors -l plain -d 'plain text, no box drawing'
complete -c wellsensors -l box -d 'force box drawing even when piped'
complete -c wellsensors -l no-emoji -d 'drop emoji icons'
complete -c wellsensors -l emoji -d 'force emoji icons'
complete -c wellsensors -l json -d 'machine-readable JSON'
complete -c wellsensors -l short -d 'one-line compact status (status bars)'
complete -c wellsensors -l html -d 'standalone HTML report page'
complete -c wellsensors -l debug -d 'shell tracing'
complete -c wellsensors -l cli -d 'live view, refresh every sec (default 2)'
