# fish completion for wellhw
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellhw --help` -- do not edit.

complete -c wellhw -f
complete -c wellhw -l help -s h -d 'show this help'
complete -c wellhw -l version -s V -d 'show version'
complete -c wellhw -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellhw -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellhw -l plain -d 'plain text, no box drawing'
complete -c wellhw -l box -d 'force box drawing even when piped'
complete -c wellhw -l no-emoji -d 'drop emoji icons'
complete -c wellhw -l emoji -d 'force emoji icons'
complete -c wellhw -l json -d 'machine-readable JSON'
complete -c wellhw -l html -d 'standalone HTML report page'
complete -c wellhw -l debug -d 'shell tracing'
complete -c wellhw -l snapshot -F -d 'save stable hardware identity to FILE'
complete -c wellhw -l diff -F -d 'compare current hardware against a snapshot'
