# fish completion for wellfetch
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellfetch --help` -- do not edit.

complete -c wellfetch -f
complete -c wellfetch -l help -s h -d 'show this help'
complete -c wellfetch -l version -s V -d 'show version'
complete -c wellfetch -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellfetch -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellfetch -l plain -d 'plain text, no box drawing'
complete -c wellfetch -l box -d 'force box drawing even when piped'
complete -c wellfetch -l no-emoji -d 'drop emoji icons'
complete -c wellfetch -l emoji -d 'force emoji icons'
complete -c wellfetch -l json -d 'machine-readable JSON'
complete -c wellfetch -l html -d 'standalone HTML report page'
complete -c wellfetch -l debug -d 'shell tracing'
complete -c wellfetch -l no-logo -l text -d 'text only, no logo'
complete -c wellfetch -l logo -d 'show logo (default on tty)'
complete -c wellfetch -l png -d 'force the PNG-rendered logo instead of distro art'
complete -c wellfetch -l all -l full -d 'show all sections (audio, resolution, peripherals…)'
complete -c wellfetch -l logo-width -x -d 'logo width in cells'
