# fish completion for wellcpu
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellcpu --help` -- do not edit.

complete -c wellcpu -f
complete -c wellcpu -l help -s h -d 'show this help'
complete -c wellcpu -l version -s V -d 'show version'
complete -c wellcpu -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellcpu -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellcpu -l plain -d 'plain text, no box drawing'
complete -c wellcpu -l box -d 'force box drawing even when piped'
complete -c wellcpu -l no-emoji -d 'drop emoji icons'
complete -c wellcpu -l emoji -d 'force emoji icons'
complete -c wellcpu -l json -d 'machine-readable JSON'
complete -c wellcpu -l short -d 'one-line compact status (status bars)'
complete -c wellcpu -l html -d 'standalone HTML report page'
complete -c wellcpu -l debug -d 'shell tracing'
