# fish completion for wellutils (launcher)
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh -- do not edit.

complete -c wellutils -f
complete -c wellutils -n '__fish_is_first_arg' -a 'usb wellusb wusb pci wellpci wpci block wellblock wblock mem wellmem wmem ram wellram wram mod wellmod wmod sensors wellsensors wsensors wtemp hw wellhw whw per wellper wper gpu wellgpu wgpu cpu wellcpu wcpu fetch wellfetch wfetch up wellup wup net wellnet wnet power wellpower wpower wbatt doctor welldoctor wdoc wdoctor html report whtml self-update selfupdate'
complete -c wellutils -n '__fish_is_first_arg' -s h -l help -d 'show help'
complete -c wellutils -n '__fish_is_first_arg' -s V -l version -d 'show version'
complete -c wellutils -n '__fish_is_first_arg' -s l -l lang -x -a 'RU EN' -d 'set default language'
complete -c wellutils -n '__fish_seen_subcommand_from usb wellusb wusb' -a '(complete -C"wellusb "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from pci wellpci wpci' -a '(complete -C"wellpci "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from block wellblock wblock' -a '(complete -C"wellblock "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from mem wellmem wmem ram wellram wram' -a '(complete -C"wellmem "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from mod wellmod wmod' -a '(complete -C"wellmod "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from sensors wellsensors wsensors wtemp' -a '(complete -C"wellsensors "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from hw wellhw whw' -a '(complete -C"wellhw "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from per wellper wper' -a '(complete -C"wellper "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from gpu wellgpu wgpu' -a '(complete -C"wellgpu "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from cpu wellcpu wcpu' -a '(complete -C"wellcpu "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from fetch wellfetch wfetch' -a '(complete -C"wellfetch "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from up wellup wup' -a '(complete -C"wellup "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from net wellnet wnet' -a '(complete -C"wellnet "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from power wellpower wpower wbatt' -a '(complete -C"wellpower "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from doctor welldoctor wdoc wdoctor' -a '(complete -C"welldoctor "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from html report whtml' -a '(complete -C"whtml "(commandline -ct))'
complete -c wellutils -n '__fish_seen_subcommand_from self-update selfupdate' -a '(complete -C"wellup "(commandline -ct))'
