# fish completion for wellnet
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellnet --help` -- do not edit.

complete -c wellnet -f
complete -c wellnet -l help -s h -d 'show this help'
complete -c wellnet -l version -s V -d 'show version'
complete -c wellnet -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellnet -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellnet -l plain -d 'plain text, no box drawing'
complete -c wellnet -l box -d 'force box drawing even when piped'
complete -c wellnet -l no-emoji -d 'drop emoji icons'
complete -c wellnet -l emoji -d 'force emoji icons'
complete -c wellnet -l json -d 'machine-readable JSON'
complete -c wellnet -l short -d 'one-line compact status (status bars)'
complete -c wellnet -l html -d 'standalone HTML report page'
complete -c wellnet -l debug -d 'shell tracing'
