# fish completion for wellup
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellup --help` -- do not edit.

complete -c wellup -f
complete -c wellup -l help -s h -d 'show this help'
complete -c wellup -l version -s V -d 'show version'
complete -c wellup -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c wellup -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c wellup -l plain -d 'plain text, no box drawing'
complete -c wellup -l box -d 'force box drawing even when piped'
complete -c wellup -l no-emoji -d 'drop emoji icons'
complete -c wellup -l emoji -d 'force emoji icons'
complete -c wellup -l json -d 'machine-readable JSON'
complete -c wellup -l html -d 'standalone HTML report page'
complete -c wellup -l debug -d 'shell tracing'
complete -c wellup -l check -l list -d 'only list available updates, do not install'
complete -c wellup -l yes -s y -d 'apply updates without confirmation'
complete -c wellup -l full -d 'apt: full-upgrade (may remove packages) instead of upgrade'
complete -c wellup -l pacnew -d 'list leftover .pacnew/.pacsave files in /etc'
complete -c wellup -l self-update -d 'update wellutils itself from GitHub'
complete -c wellup -l self -d 'alias of --self-update'
