# fish completion for welldoctor
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `welldoctor --help` -- do not edit.

complete -c welldoctor -f
complete -c welldoctor -l help -s h -d 'show this help'
complete -c welldoctor -l version -s V -d 'show version'
complete -c welldoctor -l lang -s l -x -a 'ru en auto' -d 'output language (auto = from locale)'
complete -c welldoctor -l color -x -a 'always auto never' -d 'colorize output (auto = tty)'
complete -c welldoctor -l plain -d 'plain text, no box drawing'
complete -c welldoctor -l box -d 'force box drawing even when piped'
complete -c welldoctor -l no-emoji -d 'drop emoji icons'
complete -c welldoctor -l emoji -d 'force emoji icons'
complete -c welldoctor -l json -d 'machine-readable JSON'
complete -c welldoctor -l short -d 'one-line compact status (status bars)'
complete -c welldoctor -l html -d 'standalone HTML report page'
complete -c welldoctor -l debug -d 'shell tracing'
