# fish completion for whtml
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `whtml --help` -- do not edit.

complete -c whtml -f
complete -c whtml -l output -r -F -d 'save HTML to FILE (default: ~/wellreport.html)'
complete -c whtml -l no-open -d 'do not auto-open the report in a browser'
complete -c whtml -l open -d 'force open in browser'
complete -c whtml -l ami -d 'render the classic AMI BIOS 2000s setup look'
complete -c whtml -l ai -d 'OPTIONAL AI analysis. Requires WHTML_AI_ENDPOINT to be set'
complete -c whtml -l lang -s l -x -a 'ru en auto' -d 'report language (auto = from locale; --ami is English only)'
complete -c whtml -l debug -d 'shell tracing + progress log on stderr'
complete -c whtml -l help -s h -d 'this help'
complete -c whtml -l version -s V -d 'print version'
