# bash completion for wellfetch
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `wellfetch --help` -- do not edit.

_wellfetch() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local opts="--help -h --version -V --lang -l --color --plain --box --no-emoji --emoji --json --html --debug --no-logo --text --logo --png --all --full --logo-width"

    case "$prev" in
        --lang|-l) COMPREPLY=( $(compgen -W "ru en auto" -- "$cur") ); return 0 ;;
        --color) COMPREPLY=( $(compgen -W "always auto never" -- "$cur") ); return 0 ;;
        --logo-width) return 0 ;;
    esac

    case "$cur" in
        --*=*)
            local flag="${cur%%=*}" val="${cur#*=}"
            case "$flag" in
                --lang) COMPREPLY=( $(compgen -P "$flag=" -W "ru en auto" -- "$val") ) ;;
                --color) COMPREPLY=( $(compgen -P "$flag=" -W "always auto never" -- "$val") ) ;;
            esac
            return 0 ;;
        -*) COMPREPLY=( $(compgen -W "$opts" -- "$cur") ); return 0 ;;
    esac
    return 0
}

complete -F _wellfetch wellfetch
