# bash completion for wellutils (launcher)
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh -- do not edit.

_wellutils() {
    local cur tool=""
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if (( COMP_CWORD == 1 )); then
        COMPREPLY=( $(compgen -W "usb wellusb wusb pci wellpci wpci block wellblock wblock mem wellmem wmem ram wellram wram mod wellmod wmod sensors wellsensors wsensors wtemp hw wellhw whw per wellper wper gpu wellgpu wgpu cpu wellcpu wcpu fetch wellfetch wfetch up wellup wup net wellnet wnet power wellpower wpower wbatt doctor welldoctor wdoc wdoctor html report whtml self-update selfupdate --help -h --version -V --lang -l" -- "$cur") )
        return 0
    fi
    case "${COMP_WORDS[1]}" in
        --lang|-l) COMPREPLY=( $(compgen -W "RU EN ru en" -- "$cur") ); return 0 ;;
        usb|wellusb|wusb) tool=wellusb ;;
        pci|wellpci|wpci) tool=wellpci ;;
        block|wellblock|wblock) tool=wellblock ;;
        mem|wellmem|wmem|ram|wellram|wram) tool=wellmem ;;
        mod|wellmod|wmod) tool=wellmod ;;
        sensors|wellsensors|wsensors|wtemp) tool=wellsensors ;;
        hw|wellhw|whw) tool=wellhw ;;
        per|wellper|wper) tool=wellper ;;
        gpu|wellgpu|wgpu) tool=wellgpu ;;
        cpu|wellcpu|wcpu) tool=wellcpu ;;
        fetch|wellfetch|wfetch) tool=wellfetch ;;
        up|wellup|wup) tool=wellup ;;
        net|wellnet|wnet) tool=wellnet ;;
        power|wellpower|wpower|wbatt) tool=wellpower ;;
        doctor|welldoctor|wdoc|wdoctor) tool=welldoctor ;;
        html|report|whtml) tool=whtml ;;
        self-update|selfupdate) tool=wellup ;;
        *) return 0 ;;
    esac
    # Delegate to the tool completion (load it on demand).
    declare -F "_$tool" >/dev/null 2>&1 || { declare -F _completion_loader >/dev/null 2>&1 && _completion_loader "$tool"; }
    declare -F "_$tool" >/dev/null 2>&1 || return 0
    local -a words=("$tool" "${COMP_WORDS[@]:2}")
    COMP_WORDS=("${words[@]}"); COMP_CWORD=$(( COMP_CWORD - 1 ))
    "_$tool"
}
complete -F _wellutils wellutils
