# bash completion for whtml
# Part of wellutils by wellbou_
# Generated by tools/gen-completions.sh from `whtml --help` -- do not edit.

_whtml() {
    local cur prev
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local opts="--output --no-open --open --ami --ai --lang -l --debug --help -h --version -V"

    case "$prev" in
        --lang|-l) COMPREPLY=( $(compgen -W "ru en auto" -- "$cur") ); return 0 ;;
        --output) COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;
    esac

    case "$cur" in
        --*=*)
            local flag="${cur%%=*}" val="${cur#*=}"
            case "$flag" in
                --output) COMPREPLY=( $(compgen -P "$flag=" -f -- "$val") ) ;;
                --lang) COMPREPLY=( $(compgen -P "$flag=" -W "ru en auto" -- "$val") ) ;;
            esac
            return 0 ;;
        -*) COMPREPLY=( $(compgen -W "$opts" -- "$cur") ); return 0 ;;
    esac
    return 0
}

complete -F _whtml whtml
